// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module softmax (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_0_V_read;
input  [31:0] data_1_V_read;
input  [31:0] data_2_V_read;
input  [31:0] data_3_V_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] exp_table4_address0;
reg    exp_table4_ce0;
wire   [17:0] exp_table4_q0;
wire   [9:0] exp_table4_address1;
reg    exp_table4_ce1;
wire   [17:0] exp_table4_q1;
wire   [9:0] exp_table4_address2;
reg    exp_table4_ce2;
wire   [17:0] exp_table4_q2;
wire   [9:0] exp_table4_address3;
reg    exp_table4_ce3;
wire   [17:0] exp_table4_q3;
wire   [9:0] exp_table4_address4;
reg    exp_table4_ce4;
wire   [17:0] exp_table4_q4;
wire   [9:0] exp_table4_address5;
reg    exp_table4_ce5;
wire   [17:0] exp_table4_q5;
wire   [9:0] exp_table4_address6;
reg    exp_table4_ce6;
wire   [17:0] exp_table4_q6;
wire   [9:0] exp_table4_address7;
reg    exp_table4_ce7;
wire   [17:0] exp_table4_q7;
wire   [9:0] exp_table4_address8;
reg    exp_table4_ce8;
wire   [17:0] exp_table4_q8;
wire   [9:0] exp_table4_address9;
reg    exp_table4_ce9;
wire   [17:0] exp_table4_q9;
wire   [9:0] exp_table4_address10;
reg    exp_table4_ce10;
wire   [17:0] exp_table4_q10;
wire   [9:0] exp_table4_address11;
reg    exp_table4_ce11;
wire   [17:0] exp_table4_q11;
wire   [9:0] invert_table5_address0;
reg    invert_table5_ce0;
wire   [14:0] invert_table5_q0;
wire   [9:0] invert_table5_address1;
reg    invert_table5_ce1;
wire   [14:0] invert_table5_q1;
wire   [9:0] invert_table5_address2;
reg    invert_table5_ce2;
wire   [14:0] invert_table5_q2;
wire   [9:0] invert_table5_address3;
reg    invert_table5_ce3;
wire   [14:0] invert_table5_q3;
wire   [14:0] index_0_1_cast_fu_408_p2;
reg   [14:0] index_0_1_cast_reg_2498;
reg   [0:0] tmp_111_reg_2503;
wire   [14:0] index_0_2_cast_fu_504_p2;
reg   [14:0] index_0_2_cast_reg_2508;
reg   [0:0] tmp_117_reg_2513;
wire   [14:0] index_0_3_cast_fu_600_p2;
reg   [14:0] index_0_3_cast_reg_2518;
reg   [0:0] tmp_123_reg_2523;
wire   [14:0] index_cast_fu_692_p2;
reg   [14:0] index_cast_reg_2528;
reg   [0:0] tmp_129_reg_2533;
wire   [14:0] index_116_2_cast_fu_784_p2;
reg   [14:0] index_116_2_cast_reg_2538;
reg   [0:0] tmp_135_reg_2543;
wire   [14:0] index_116_3_cast_fu_876_p2;
reg   [14:0] index_116_3_cast_reg_2548;
reg   [0:0] tmp_141_reg_2553;
wire   [14:0] index_2_cast_fu_968_p2;
reg   [14:0] index_2_cast_reg_2558;
reg   [0:0] tmp_147_reg_2563;
wire   [14:0] index_2_1_cast_fu_1060_p2;
reg   [14:0] index_2_1_cast_reg_2568;
reg   [0:0] tmp_153_reg_2573;
wire   [14:0] index_2_3_cast_fu_1152_p2;
reg   [14:0] index_2_3_cast_reg_2578;
reg   [0:0] tmp_159_reg_2583;
wire   [14:0] index_3_cast_fu_1244_p2;
reg   [14:0] index_3_cast_reg_2588;
reg   [0:0] tmp_165_reg_2593;
wire   [14:0] index_3_1_cast_fu_1336_p2;
reg   [14:0] index_3_1_cast_reg_2598;
reg   [0:0] tmp_171_reg_2603;
wire   [14:0] index_3_2_cast_fu_1428_p2;
reg   [14:0] index_3_2_cast_reg_2608;
reg   [0:0] tmp_177_reg_2613;
reg   [17:0] exp_table4_load_2_reg_2678;
wire   [17:0] tmp2_fu_1910_p2;
reg   [17:0] tmp2_reg_2683;
reg   [17:0] exp_table4_load_5_reg_2688;
wire   [17:0] tmp5_fu_1916_p2;
reg   [17:0] tmp5_reg_2693;
reg   [17:0] exp_table4_load_8_reg_2698;
wire   [17:0] tmp8_fu_1922_p2;
reg   [17:0] tmp8_reg_2703;
reg   [17:0] exp_table4_load_9_reg_2708;
wire   [17:0] tmp11_fu_1928_p2;
reg   [17:0] tmp11_reg_2713;
wire   [9:0] tmp_184_fu_2056_p1;
reg   [9:0] tmp_184_reg_2718;
reg   [1:0] tmp_185_reg_2723;
wire   [9:0] tmp_190_fu_2152_p1;
reg   [9:0] tmp_190_reg_2728;
reg   [1:0] tmp_191_reg_2733;
wire   [9:0] tmp_196_fu_2248_p1;
reg   [9:0] tmp_196_reg_2738;
reg   [1:0] tmp_197_reg_2743;
wire   [9:0] tmp_202_fu_2344_p1;
reg   [9:0] tmp_202_reg_2748;
reg   [1:0] tmp_203_reg_2753;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] tmp_92_0_1_fu_1476_p1;
wire   [63:0] tmp_92_0_2_fu_1515_p1;
wire   [63:0] tmp_92_0_3_fu_1554_p1;
wire   [63:0] tmp_92_1_fu_1593_p1;
wire   [63:0] tmp_92_1_2_fu_1632_p1;
wire   [63:0] tmp_92_1_3_fu_1671_p1;
wire   [63:0] tmp_92_2_fu_1710_p1;
wire   [63:0] tmp_92_2_1_fu_1749_p1;
wire   [63:0] tmp_92_2_3_fu_1788_p1;
wire   [63:0] tmp_92_3_fu_1827_p1;
wire   [63:0] tmp_92_3_1_fu_1866_p1;
wire   [63:0] tmp_92_3_2_fu_1905_p1;
wire   [63:0] tmp_85_fu_2370_p1;
wire   [63:0] tmp_86_1_fu_2387_p1;
wire   [63:0] tmp_86_2_fu_2404_p1;
wire   [63:0] tmp_86_3_fu_2421_p1;
wire  signed [32:0] tmp_79_0_1_fu_322_p1;
wire  signed [32:0] tmp_80_0_1_fu_326_p1;
wire   [32:0] r_V_0_1_fu_330_p2;
wire   [14:0] tmp_s_fu_336_p4;
wire   [17:0] tmp_108_fu_358_p1;
wire   [23:0] p_Result_84_0_1_fu_362_p3;
wire  signed [15:0] p_Result_82_0_1_ca_fu_346_p1;
wire   [0:0] tmp_89_0_1_fu_370_p2;
wire   [15:0] ret_V_21_0_1_fu_376_p2;
wire   [0:0] tmp_106_fu_350_p3;
wire   [15:0] p_0_1_fu_382_p3;
wire   [15:0] p_5_0_1_fu_390_p3;
wire   [14:0] tmp_110_fu_398_p1;
wire   [15:0] index_0_1_fu_402_p2;
wire  signed [32:0] tmp_79_0_2_fu_422_p1;
wire   [32:0] r_V_0_2_fu_426_p2;
wire   [14:0] tmp_66_fu_432_p4;
wire   [17:0] tmp_115_fu_454_p1;
wire   [23:0] p_Result_84_0_2_fu_458_p3;
wire  signed [15:0] p_Result_82_0_2_ca_fu_442_p1;
wire   [0:0] tmp_89_0_2_fu_466_p2;
wire   [15:0] ret_V_21_0_2_fu_472_p2;
wire   [0:0] tmp_114_fu_446_p3;
wire   [15:0] p_0_2_fu_478_p3;
wire   [15:0] p_5_0_2_fu_486_p3;
wire   [14:0] tmp_116_fu_494_p1;
wire   [15:0] index_0_2_fu_498_p2;
wire  signed [32:0] tmp_79_0_3_fu_518_p1;
wire   [32:0] r_V_0_3_fu_522_p2;
wire   [14:0] tmp_69_fu_528_p4;
wire   [17:0] tmp_121_fu_550_p1;
wire   [23:0] p_Result_84_0_3_fu_554_p3;
wire  signed [15:0] p_Result_82_0_3_ca_fu_538_p1;
wire   [0:0] tmp_89_0_3_fu_562_p2;
wire   [15:0] ret_V_21_0_3_fu_568_p2;
wire   [0:0] tmp_120_fu_542_p3;
wire   [15:0] p_0_3_fu_574_p3;
wire   [15:0] p_5_0_3_fu_582_p3;
wire   [14:0] tmp_122_fu_590_p1;
wire   [15:0] index_0_3_fu_594_p2;
wire   [32:0] r_V_1_fu_614_p2;
wire   [14:0] tmp_72_fu_620_p4;
wire   [17:0] tmp_127_fu_642_p1;
wire   [23:0] p_Result_84_1_fu_646_p3;
wire  signed [15:0] p_Result_82_1_cast_fu_630_p1;
wire   [0:0] tmp_89_1_fu_654_p2;
wire   [15:0] ret_V_21_1_fu_660_p2;
wire   [0:0] tmp_126_fu_634_p3;
wire   [15:0] p_1_fu_666_p3;
wire   [15:0] p_5_1_fu_674_p3;
wire   [14:0] tmp_128_fu_682_p1;
wire   [15:0] index_s_fu_686_p2;
wire   [32:0] r_V_1_2_fu_706_p2;
wire   [14:0] tmp_75_fu_712_p4;
wire   [17:0] tmp_133_fu_734_p1;
wire   [23:0] p_Result_84_1_2_fu_738_p3;
wire  signed [15:0] p_Result_82_1_2_ca_fu_722_p1;
wire   [0:0] tmp_89_1_2_fu_746_p2;
wire   [15:0] ret_V_21_1_2_fu_752_p2;
wire   [0:0] tmp_132_fu_726_p3;
wire   [15:0] p_1_2_fu_758_p3;
wire   [15:0] p_5_1_2_fu_766_p3;
wire   [14:0] tmp_134_fu_774_p1;
wire   [15:0] index_116_2_fu_778_p2;
wire   [32:0] r_V_1_3_fu_798_p2;
wire   [14:0] tmp_76_fu_804_p4;
wire   [17:0] tmp_139_fu_826_p1;
wire   [23:0] p_Result_84_1_3_fu_830_p3;
wire  signed [15:0] p_Result_82_1_3_ca_fu_814_p1;
wire   [0:0] tmp_89_1_3_fu_838_p2;
wire   [15:0] ret_V_21_1_3_fu_844_p2;
wire   [0:0] tmp_138_fu_818_p3;
wire   [15:0] p_1_3_fu_850_p3;
wire   [15:0] p_5_1_3_fu_858_p3;
wire   [14:0] tmp_140_fu_866_p1;
wire   [15:0] index_116_3_fu_870_p2;
wire   [32:0] r_V_2_fu_890_p2;
wire   [14:0] tmp_78_fu_896_p4;
wire   [17:0] tmp_145_fu_918_p1;
wire   [23:0] p_Result_84_2_fu_922_p3;
wire  signed [15:0] p_Result_82_2_cast_fu_906_p1;
wire   [0:0] tmp_89_2_fu_930_p2;
wire   [15:0] ret_V_21_2_fu_936_p2;
wire   [0:0] tmp_144_fu_910_p3;
wire   [15:0] p_2_fu_942_p3;
wire   [15:0] p_5_2_fu_950_p3;
wire   [14:0] tmp_146_fu_958_p1;
wire   [15:0] index_2_fu_962_p2;
wire   [32:0] r_V_2_1_fu_982_p2;
wire   [14:0] tmp_79_fu_988_p4;
wire   [17:0] tmp_151_fu_1010_p1;
wire   [23:0] p_Result_84_2_1_fu_1014_p3;
wire  signed [15:0] p_Result_82_2_1_ca_fu_998_p1;
wire   [0:0] tmp_89_2_1_fu_1022_p2;
wire   [15:0] ret_V_21_2_1_fu_1028_p2;
wire   [0:0] tmp_150_fu_1002_p3;
wire   [15:0] p_2_1_fu_1034_p3;
wire   [15:0] p_5_2_1_fu_1042_p3;
wire   [14:0] tmp_152_fu_1050_p1;
wire   [15:0] index_2_1_fu_1054_p2;
wire   [32:0] r_V_2_3_fu_1074_p2;
wire   [14:0] tmp_80_fu_1080_p4;
wire   [17:0] tmp_157_fu_1102_p1;
wire   [23:0] p_Result_84_2_3_fu_1106_p3;
wire  signed [15:0] p_Result_82_2_3_ca_fu_1090_p1;
wire   [0:0] tmp_89_2_3_fu_1114_p2;
wire   [15:0] ret_V_21_2_3_fu_1120_p2;
wire   [0:0] tmp_156_fu_1094_p3;
wire   [15:0] p_2_3_fu_1126_p3;
wire   [15:0] p_5_2_3_fu_1134_p3;
wire   [14:0] tmp_158_fu_1142_p1;
wire   [15:0] index_2_3_fu_1146_p2;
wire   [32:0] r_V_3_fu_1166_p2;
wire   [14:0] tmp_81_fu_1172_p4;
wire   [17:0] tmp_163_fu_1194_p1;
wire   [23:0] p_Result_84_3_fu_1198_p3;
wire  signed [15:0] p_Result_82_3_cast_fu_1182_p1;
wire   [0:0] tmp_89_3_fu_1206_p2;
wire   [15:0] ret_V_21_3_fu_1212_p2;
wire   [0:0] tmp_162_fu_1186_p3;
wire   [15:0] p_3_fu_1218_p3;
wire   [15:0] p_5_3_fu_1226_p3;
wire   [14:0] tmp_164_fu_1234_p1;
wire   [15:0] index_3_fu_1238_p2;
wire   [32:0] r_V_3_1_fu_1258_p2;
wire   [14:0] tmp_82_fu_1264_p4;
wire   [17:0] tmp_169_fu_1286_p1;
wire   [23:0] p_Result_84_3_1_fu_1290_p3;
wire  signed [15:0] p_Result_82_3_1_ca_fu_1274_p1;
wire   [0:0] tmp_89_3_1_fu_1298_p2;
wire   [15:0] ret_V_21_3_1_fu_1304_p2;
wire   [0:0] tmp_168_fu_1278_p3;
wire   [15:0] p_3_1_50_fu_1310_p3;
wire   [15:0] p_5_3_1_fu_1318_p3;
wire   [14:0] tmp_170_fu_1326_p1;
wire   [15:0] index_3_1_fu_1330_p2;
wire   [32:0] r_V_3_2_fu_1350_p2;
wire   [14:0] tmp_83_fu_1356_p4;
wire   [17:0] tmp_175_fu_1378_p1;
wire   [23:0] p_Result_84_3_2_fu_1382_p3;
wire  signed [15:0] p_Result_82_3_2_ca_fu_1366_p1;
wire   [0:0] tmp_89_3_2_fu_1390_p2;
wire   [15:0] ret_V_21_3_2_fu_1396_p2;
wire   [0:0] tmp_174_fu_1370_p3;
wire   [15:0] p_3_2_51_fu_1402_p3;
wire   [15:0] p_5_3_2_fu_1410_p3;
wire   [14:0] tmp_176_fu_1418_p1;
wire   [15:0] index_3_2_fu_1422_p2;
wire   [14:0] p_3_0_1_fu_1442_p3;
wire   [4:0] tmp_113_fu_1452_p4;
wire   [0:0] icmp_fu_1462_p2;
wire   [9:0] tmp_112_fu_1448_p1;
wire   [9:0] index_1_0_1_fu_1468_p3;
wire   [14:0] p_3_0_2_fu_1481_p3;
wire   [4:0] tmp_119_fu_1491_p4;
wire   [0:0] icmp1_fu_1501_p2;
wire   [9:0] tmp_118_fu_1487_p1;
wire   [9:0] index_1_0_2_fu_1507_p3;
wire   [14:0] p_3_0_3_fu_1520_p3;
wire   [4:0] tmp_125_fu_1530_p4;
wire   [0:0] icmp2_fu_1540_p2;
wire   [9:0] tmp_124_fu_1526_p1;
wire   [9:0] index_1_0_3_fu_1546_p3;
wire   [14:0] p_3_1_fu_1559_p3;
wire   [4:0] tmp_131_fu_1569_p4;
wire   [0:0] icmp3_fu_1579_p2;
wire   [9:0] tmp_130_fu_1565_p1;
wire   [9:0] index_1_1_fu_1585_p3;
wire   [14:0] p_3_1_2_fu_1598_p3;
wire   [4:0] tmp_137_fu_1608_p4;
wire   [0:0] icmp4_fu_1618_p2;
wire   [9:0] tmp_136_fu_1604_p1;
wire   [9:0] index_1_1_2_fu_1624_p3;
wire   [14:0] p_3_1_3_fu_1637_p3;
wire   [4:0] tmp_143_fu_1647_p4;
wire   [0:0] icmp5_fu_1657_p2;
wire   [9:0] tmp_142_fu_1643_p1;
wire   [9:0] index_1_1_3_fu_1663_p3;
wire   [14:0] p_3_2_fu_1676_p3;
wire   [4:0] tmp_149_fu_1686_p4;
wire   [0:0] icmp6_fu_1696_p2;
wire   [9:0] tmp_148_fu_1682_p1;
wire   [9:0] index_1_2_fu_1702_p3;
wire   [14:0] p_3_2_1_fu_1715_p3;
wire   [4:0] tmp_155_fu_1725_p4;
wire   [0:0] icmp7_fu_1735_p2;
wire   [9:0] tmp_154_fu_1721_p1;
wire   [9:0] index_1_2_1_fu_1741_p3;
wire   [14:0] p_3_2_3_fu_1754_p3;
wire   [4:0] tmp_161_fu_1764_p4;
wire   [0:0] icmp8_fu_1774_p2;
wire   [9:0] tmp_160_fu_1760_p1;
wire   [9:0] index_1_2_3_fu_1780_p3;
wire   [14:0] p_3_3_fu_1793_p3;
wire   [4:0] tmp_167_fu_1803_p4;
wire   [0:0] icmp9_fu_1813_p2;
wire   [9:0] tmp_166_fu_1799_p1;
wire   [9:0] index_1_3_fu_1819_p3;
wire   [14:0] p_3_3_1_fu_1832_p3;
wire   [4:0] tmp_173_fu_1842_p4;
wire   [0:0] icmp10_fu_1852_p2;
wire   [9:0] tmp_172_fu_1838_p1;
wire   [9:0] index_1_3_1_fu_1858_p3;
wire   [14:0] p_3_3_2_fu_1871_p3;
wire   [4:0] tmp_179_fu_1881_p4;
wire   [0:0] icmp11_fu_1891_p2;
wire   [9:0] tmp_178_fu_1877_p1;
wire   [9:0] index_1_3_2_fu_1897_p3;
wire   [17:0] tmp3_fu_1934_p2;
wire   [17:0] tmp6_fu_1944_p2;
wire   [17:0] tmp9_fu_1954_p2;
wire   [17:0] tmp12_fu_1964_p2;
wire   [17:0] p_Val2_63_0_3_fu_1939_p2;
wire   [11:0] tmp_84_fu_1974_p4;
wire   [5:0] tmp_181_fu_1996_p1;
wire   [9:0] p_Result_4_fu_2000_p3;
wire  signed [12:0] p_Result_cast_fu_1984_p1;
wire   [0:0] tmp_77_fu_2008_p2;
wire   [12:0] ret_V_s_fu_2014_p2;
wire   [0:0] tmp_180_fu_1988_p3;
wire   [12:0] p_1_52_fu_2020_p3;
wire   [12:0] p_4_fu_2028_p3;
wire   [0:0] tmp_183_fu_2040_p3;
wire   [11:0] tmp_182_fu_2036_p1;
wire   [11:0] p_2_53_fu_2048_p3;
wire   [17:0] p_Val2_63_1_3_fu_1949_p2;
wire   [11:0] tmp_86_fu_2070_p4;
wire   [5:0] tmp_187_fu_2092_p1;
wire   [9:0] p_Result_81_1_fu_2096_p3;
wire  signed [12:0] p_Result_1_cast_fu_2080_p1;
wire   [0:0] tmp_77_1_fu_2104_p2;
wire   [12:0] ret_V_19_1_fu_2110_p2;
wire   [0:0] tmp_186_fu_2084_p3;
wire   [12:0] p_1_1_fu_2116_p3;
wire   [12:0] p_4_1_fu_2124_p3;
wire   [0:0] tmp_189_fu_2136_p3;
wire   [11:0] tmp_188_fu_2132_p1;
wire   [11:0] p_2_1_54_fu_2144_p3;
wire   [17:0] p_Val2_63_2_3_fu_1959_p2;
wire   [11:0] tmp_87_fu_2166_p4;
wire   [5:0] tmp_193_fu_2188_p1;
wire   [9:0] p_Result_81_2_fu_2192_p3;
wire  signed [12:0] p_Result_2_cast_fu_2176_p1;
wire   [0:0] tmp_77_2_fu_2200_p2;
wire   [12:0] ret_V_19_2_fu_2206_p2;
wire   [0:0] tmp_192_fu_2180_p3;
wire   [12:0] p_1_2_55_fu_2212_p3;
wire   [12:0] p_4_2_fu_2220_p3;
wire   [0:0] tmp_195_fu_2232_p3;
wire   [11:0] tmp_194_fu_2228_p1;
wire   [11:0] p_2_2_fu_2240_p3;
wire   [17:0] p_Val2_63_3_3_fu_1969_p2;
wire   [11:0] tmp_88_fu_2262_p4;
wire   [5:0] tmp_199_fu_2284_p1;
wire   [9:0] p_Result_81_3_fu_2288_p3;
wire  signed [12:0] p_Result_3_cast_fu_2272_p1;
wire   [0:0] tmp_77_3_fu_2296_p2;
wire   [12:0] ret_V_19_3_fu_2302_p2;
wire   [0:0] tmp_198_fu_2276_p3;
wire   [12:0] p_1_3_56_fu_2308_p3;
wire   [12:0] p_4_3_fu_2316_p3;
wire   [0:0] tmp_201_fu_2328_p3;
wire   [11:0] tmp_200_fu_2324_p1;
wire   [11:0] p_2_3_57_fu_2336_p3;
wire   [0:0] icmp12_fu_2358_p2;
wire   [9:0] exp_res_index_1_fu_2363_p3;
wire   [0:0] icmp13_fu_2375_p2;
wire   [9:0] exp_res_index_1_1_fu_2380_p3;
wire   [0:0] icmp14_fu_2392_p2;
wire   [9:0] exp_res_index_1_2_fu_2397_p3;
wire   [0:0] icmp15_fu_2409_p2;
wire   [9:0] exp_res_index_1_3_fu_2414_p3;
wire   [28:0] res_0_V_write_assig_fu_2426_p3;
wire   [28:0] res_1_V_write_assig_fu_2438_p3;
wire   [28:0] res_2_V_write_assig_fu_2450_p3;
wire   [28:0] res_3_V_write_assig_fu_2462_p3;
wire   [31:0] res_0_V_write_assig_1_fu_2434_p1;
wire   [31:0] res_1_V_write_assig_1_fu_2446_p1;
wire   [31:0] res_2_V_write_assig_1_fu_2458_p1;
wire   [31:0] res_3_V_write_assig_1_fu_2470_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

softmax_exp_table4 #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table4_address0),
    .ce0(exp_table4_ce0),
    .q0(exp_table4_q0),
    .address1(exp_table4_address1),
    .ce1(exp_table4_ce1),
    .q1(exp_table4_q1),
    .address2(exp_table4_address2),
    .ce2(exp_table4_ce2),
    .q2(exp_table4_q2),
    .address3(exp_table4_address3),
    .ce3(exp_table4_ce3),
    .q3(exp_table4_q3),
    .address4(exp_table4_address4),
    .ce4(exp_table4_ce4),
    .q4(exp_table4_q4),
    .address5(exp_table4_address5),
    .ce5(exp_table4_ce5),
    .q5(exp_table4_q5),
    .address6(exp_table4_address6),
    .ce6(exp_table4_ce6),
    .q6(exp_table4_q6),
    .address7(exp_table4_address7),
    .ce7(exp_table4_ce7),
    .q7(exp_table4_q7),
    .address8(exp_table4_address8),
    .ce8(exp_table4_ce8),
    .q8(exp_table4_q8),
    .address9(exp_table4_address9),
    .ce9(exp_table4_ce9),
    .q9(exp_table4_q9),
    .address10(exp_table4_address10),
    .ce10(exp_table4_ce10),
    .q10(exp_table4_q10),
    .address11(exp_table4_address11),
    .ce11(exp_table4_ce11),
    .q11(exp_table4_q11)
);

softmax_invert_taAem #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table5_address0),
    .ce0(invert_table5_ce0),
    .q0(invert_table5_q0),
    .address1(invert_table5_address1),
    .ce1(invert_table5_ce1),
    .q1(invert_table5_q1),
    .address2(invert_table5_address2),
    .ce2(invert_table5_ce2),
    .q2(invert_table5_q2),
    .address3(invert_table5_address3),
    .ce3(invert_table5_ce3),
    .q3(invert_table5_q3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        exp_table4_load_2_reg_2678 <= exp_table4_q2;
        exp_table4_load_5_reg_2688 <= exp_table4_q5;
        exp_table4_load_8_reg_2698 <= exp_table4_q8;
        exp_table4_load_9_reg_2708 <= exp_table4_q9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        index_0_1_cast_reg_2498 <= index_0_1_cast_fu_408_p2;
        index_0_2_cast_reg_2508 <= index_0_2_cast_fu_504_p2;
        index_0_3_cast_reg_2518 <= index_0_3_cast_fu_600_p2;
        index_116_2_cast_reg_2538 <= index_116_2_cast_fu_784_p2;
        index_116_3_cast_reg_2548 <= index_116_3_cast_fu_876_p2;
        index_2_1_cast_reg_2568 <= index_2_1_cast_fu_1060_p2;
        index_2_3_cast_reg_2578 <= index_2_3_cast_fu_1152_p2;
        index_2_cast_reg_2558 <= index_2_cast_fu_968_p2;
        index_3_1_cast_reg_2598 <= index_3_1_cast_fu_1336_p2;
        index_3_2_cast_reg_2608 <= index_3_2_cast_fu_1428_p2;
        index_3_cast_reg_2588 <= index_3_cast_fu_1244_p2;
        index_cast_reg_2528 <= index_cast_fu_692_p2;
        tmp_111_reg_2503 <= index_0_1_fu_402_p2[32'd15];
        tmp_117_reg_2513 <= index_0_2_fu_498_p2[32'd15];
        tmp_123_reg_2523 <= index_0_3_fu_594_p2[32'd15];
        tmp_129_reg_2533 <= index_s_fu_686_p2[32'd15];
        tmp_135_reg_2543 <= index_116_2_fu_778_p2[32'd15];
        tmp_141_reg_2553 <= index_116_3_fu_870_p2[32'd15];
        tmp_147_reg_2563 <= index_2_fu_962_p2[32'd15];
        tmp_153_reg_2573 <= index_2_1_fu_1054_p2[32'd15];
        tmp_159_reg_2583 <= index_2_3_fu_1146_p2[32'd15];
        tmp_165_reg_2593 <= index_3_fu_1238_p2[32'd15];
        tmp_171_reg_2603 <= index_3_1_fu_1330_p2[32'd15];
        tmp_177_reg_2613 <= index_3_2_fu_1422_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp11_reg_2713 <= tmp11_fu_1928_p2;
        tmp2_reg_2683 <= tmp2_fu_1910_p2;
        tmp5_reg_2693 <= tmp5_fu_1916_p2;
        tmp8_reg_2703 <= tmp8_fu_1922_p2;
        tmp_184_reg_2718 <= tmp_184_fu_2056_p1;
        tmp_185_reg_2723 <= {{p_2_53_fu_2048_p3[11:10]}};
        tmp_190_reg_2728 <= tmp_190_fu_2152_p1;
        tmp_191_reg_2733 <= {{p_2_1_54_fu_2144_p3[11:10]}};
        tmp_196_reg_2738 <= tmp_196_fu_2248_p1;
        tmp_197_reg_2743 <= {{p_2_2_fu_2240_p3[11:10]}};
        tmp_202_reg_2748 <= tmp_202_fu_2344_p1;
        tmp_203_reg_2753 <= {{p_2_3_57_fu_2336_p3[11:10]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce0 = 1'b1;
    end else begin
        exp_table4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce1 = 1'b1;
    end else begin
        exp_table4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce10 = 1'b1;
    end else begin
        exp_table4_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce11 = 1'b1;
    end else begin
        exp_table4_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce2 = 1'b1;
    end else begin
        exp_table4_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce3 = 1'b1;
    end else begin
        exp_table4_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce4 = 1'b1;
    end else begin
        exp_table4_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce5 = 1'b1;
    end else begin
        exp_table4_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce6 = 1'b1;
    end else begin
        exp_table4_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce7 = 1'b1;
    end else begin
        exp_table4_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce8 = 1'b1;
    end else begin
        exp_table4_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table4_ce9 = 1'b1;
    end else begin
        exp_table4_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table5_ce0 = 1'b1;
    end else begin
        invert_table5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table5_ce1 = 1'b1;
    end else begin
        invert_table5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table5_ce2 = 1'b1;
    end else begin
        invert_table5_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table5_ce3 = 1'b1;
    end else begin
        invert_table5_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = res_0_V_write_assig_1_fu_2434_p1;

assign ap_return_1 = res_1_V_write_assig_1_fu_2446_p1;

assign ap_return_2 = res_2_V_write_assig_1_fu_2458_p1;

assign ap_return_3 = res_3_V_write_assig_1_fu_2470_p1;

assign exp_res_index_1_1_fu_2380_p3 = ((icmp13_fu_2375_p2[0:0] === 1'b1) ? 10'd1023 : tmp_190_reg_2728);

assign exp_res_index_1_2_fu_2397_p3 = ((icmp14_fu_2392_p2[0:0] === 1'b1) ? 10'd1023 : tmp_196_reg_2738);

assign exp_res_index_1_3_fu_2414_p3 = ((icmp15_fu_2409_p2[0:0] === 1'b1) ? 10'd1023 : tmp_202_reg_2748);

assign exp_res_index_1_fu_2363_p3 = ((icmp12_fu_2358_p2[0:0] === 1'b1) ? 10'd1023 : tmp_184_reg_2718);

assign exp_table4_address0 = tmp_92_0_1_fu_1476_p1;

assign exp_table4_address1 = tmp_92_0_2_fu_1515_p1;

assign exp_table4_address10 = tmp_92_3_1_fu_1866_p1;

assign exp_table4_address11 = tmp_92_3_2_fu_1905_p1;

assign exp_table4_address2 = tmp_92_0_3_fu_1554_p1;

assign exp_table4_address3 = tmp_92_1_fu_1593_p1;

assign exp_table4_address4 = tmp_92_1_2_fu_1632_p1;

assign exp_table4_address5 = tmp_92_1_3_fu_1671_p1;

assign exp_table4_address6 = tmp_92_2_fu_1710_p1;

assign exp_table4_address7 = tmp_92_2_1_fu_1749_p1;

assign exp_table4_address8 = tmp_92_2_3_fu_1788_p1;

assign exp_table4_address9 = tmp_92_3_fu_1827_p1;

assign icmp10_fu_1852_p2 = ((tmp_173_fu_1842_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp11_fu_1891_p2 = ((tmp_179_fu_1881_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp12_fu_2358_p2 = ((tmp_185_reg_2723 != 2'd0) ? 1'b1 : 1'b0);

assign icmp13_fu_2375_p2 = ((tmp_191_reg_2733 != 2'd0) ? 1'b1 : 1'b0);

assign icmp14_fu_2392_p2 = ((tmp_197_reg_2743 != 2'd0) ? 1'b1 : 1'b0);

assign icmp15_fu_2409_p2 = ((tmp_203_reg_2753 != 2'd0) ? 1'b1 : 1'b0);

assign icmp1_fu_1501_p2 = ((tmp_119_fu_1491_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_1540_p2 = ((tmp_125_fu_1530_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp3_fu_1579_p2 = ((tmp_131_fu_1569_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_1618_p2 = ((tmp_137_fu_1608_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp5_fu_1657_p2 = ((tmp_143_fu_1647_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp6_fu_1696_p2 = ((tmp_149_fu_1686_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_1735_p2 = ((tmp_155_fu_1725_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_1774_p2 = ((tmp_161_fu_1764_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp9_fu_1813_p2 = ((tmp_167_fu_1803_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_fu_1462_p2 = ((tmp_113_fu_1452_p4 != 5'd0) ? 1'b1 : 1'b0);

assign index_0_1_cast_fu_408_p2 = (15'd512 + tmp_110_fu_398_p1);

assign index_0_1_fu_402_p2 = (16'd512 + p_5_0_1_fu_390_p3);

assign index_0_2_cast_fu_504_p2 = (15'd512 + tmp_116_fu_494_p1);

assign index_0_2_fu_498_p2 = (16'd512 + p_5_0_2_fu_486_p3);

assign index_0_3_cast_fu_600_p2 = (15'd512 + tmp_122_fu_590_p1);

assign index_0_3_fu_594_p2 = (16'd512 + p_5_0_3_fu_582_p3);

assign index_116_2_cast_fu_784_p2 = (15'd512 + tmp_134_fu_774_p1);

assign index_116_2_fu_778_p2 = (16'd512 + p_5_1_2_fu_766_p3);

assign index_116_3_cast_fu_876_p2 = (15'd512 + tmp_140_fu_866_p1);

assign index_116_3_fu_870_p2 = (16'd512 + p_5_1_3_fu_858_p3);

assign index_1_0_1_fu_1468_p3 = ((icmp_fu_1462_p2[0:0] === 1'b1) ? 10'd1023 : tmp_112_fu_1448_p1);

assign index_1_0_2_fu_1507_p3 = ((icmp1_fu_1501_p2[0:0] === 1'b1) ? 10'd1023 : tmp_118_fu_1487_p1);

assign index_1_0_3_fu_1546_p3 = ((icmp2_fu_1540_p2[0:0] === 1'b1) ? 10'd1023 : tmp_124_fu_1526_p1);

assign index_1_1_2_fu_1624_p3 = ((icmp4_fu_1618_p2[0:0] === 1'b1) ? 10'd1023 : tmp_136_fu_1604_p1);

assign index_1_1_3_fu_1663_p3 = ((icmp5_fu_1657_p2[0:0] === 1'b1) ? 10'd1023 : tmp_142_fu_1643_p1);

assign index_1_1_fu_1585_p3 = ((icmp3_fu_1579_p2[0:0] === 1'b1) ? 10'd1023 : tmp_130_fu_1565_p1);

assign index_1_2_1_fu_1741_p3 = ((icmp7_fu_1735_p2[0:0] === 1'b1) ? 10'd1023 : tmp_154_fu_1721_p1);

assign index_1_2_3_fu_1780_p3 = ((icmp8_fu_1774_p2[0:0] === 1'b1) ? 10'd1023 : tmp_160_fu_1760_p1);

assign index_1_2_fu_1702_p3 = ((icmp6_fu_1696_p2[0:0] === 1'b1) ? 10'd1023 : tmp_148_fu_1682_p1);

assign index_1_3_1_fu_1858_p3 = ((icmp10_fu_1852_p2[0:0] === 1'b1) ? 10'd1023 : tmp_172_fu_1838_p1);

assign index_1_3_2_fu_1897_p3 = ((icmp11_fu_1891_p2[0:0] === 1'b1) ? 10'd1023 : tmp_178_fu_1877_p1);

assign index_1_3_fu_1819_p3 = ((icmp9_fu_1813_p2[0:0] === 1'b1) ? 10'd1023 : tmp_166_fu_1799_p1);

assign index_2_1_cast_fu_1060_p2 = (15'd512 + tmp_152_fu_1050_p1);

assign index_2_1_fu_1054_p2 = (16'd512 + p_5_2_1_fu_1042_p3);

assign index_2_3_cast_fu_1152_p2 = (15'd512 + tmp_158_fu_1142_p1);

assign index_2_3_fu_1146_p2 = (16'd512 + p_5_2_3_fu_1134_p3);

assign index_2_cast_fu_968_p2 = (15'd512 + tmp_146_fu_958_p1);

assign index_2_fu_962_p2 = (16'd512 + p_5_2_fu_950_p3);

assign index_3_1_cast_fu_1336_p2 = (15'd512 + tmp_170_fu_1326_p1);

assign index_3_1_fu_1330_p2 = (16'd512 + p_5_3_1_fu_1318_p3);

assign index_3_2_cast_fu_1428_p2 = (15'd512 + tmp_176_fu_1418_p1);

assign index_3_2_fu_1422_p2 = (16'd512 + p_5_3_2_fu_1410_p3);

assign index_3_cast_fu_1244_p2 = (15'd512 + tmp_164_fu_1234_p1);

assign index_3_fu_1238_p2 = (16'd512 + p_5_3_fu_1226_p3);

assign index_cast_fu_692_p2 = (15'd512 + tmp_128_fu_682_p1);

assign index_s_fu_686_p2 = (16'd512 + p_5_1_fu_674_p3);

assign invert_table5_address0 = tmp_85_fu_2370_p1;

assign invert_table5_address1 = tmp_86_1_fu_2387_p1;

assign invert_table5_address2 = tmp_86_2_fu_2404_p1;

assign invert_table5_address3 = tmp_86_3_fu_2421_p1;

assign p_0_1_fu_382_p3 = ((tmp_89_0_1_fu_370_p2[0:0] === 1'b1) ? p_Result_82_0_1_ca_fu_346_p1 : ret_V_21_0_1_fu_376_p2);

assign p_0_2_fu_478_p3 = ((tmp_89_0_2_fu_466_p2[0:0] === 1'b1) ? p_Result_82_0_2_ca_fu_442_p1 : ret_V_21_0_2_fu_472_p2);

assign p_0_3_fu_574_p3 = ((tmp_89_0_3_fu_562_p2[0:0] === 1'b1) ? p_Result_82_0_3_ca_fu_538_p1 : ret_V_21_0_3_fu_568_p2);

assign p_1_1_fu_2116_p3 = ((tmp_77_1_fu_2104_p2[0:0] === 1'b1) ? p_Result_1_cast_fu_2080_p1 : ret_V_19_1_fu_2110_p2);

assign p_1_2_55_fu_2212_p3 = ((tmp_77_2_fu_2200_p2[0:0] === 1'b1) ? p_Result_2_cast_fu_2176_p1 : ret_V_19_2_fu_2206_p2);

assign p_1_2_fu_758_p3 = ((tmp_89_1_2_fu_746_p2[0:0] === 1'b1) ? p_Result_82_1_2_ca_fu_722_p1 : ret_V_21_1_2_fu_752_p2);

assign p_1_3_56_fu_2308_p3 = ((tmp_77_3_fu_2296_p2[0:0] === 1'b1) ? p_Result_3_cast_fu_2272_p1 : ret_V_19_3_fu_2302_p2);

assign p_1_3_fu_850_p3 = ((tmp_89_1_3_fu_838_p2[0:0] === 1'b1) ? p_Result_82_1_3_ca_fu_814_p1 : ret_V_21_1_3_fu_844_p2);

assign p_1_52_fu_2020_p3 = ((tmp_77_fu_2008_p2[0:0] === 1'b1) ? p_Result_cast_fu_1984_p1 : ret_V_s_fu_2014_p2);

assign p_1_fu_666_p3 = ((tmp_89_1_fu_654_p2[0:0] === 1'b1) ? p_Result_82_1_cast_fu_630_p1 : ret_V_21_1_fu_660_p2);

assign p_2_1_54_fu_2144_p3 = ((tmp_189_fu_2136_p3[0:0] === 1'b1) ? 12'd0 : tmp_188_fu_2132_p1);

assign p_2_1_fu_1034_p3 = ((tmp_89_2_1_fu_1022_p2[0:0] === 1'b1) ? p_Result_82_2_1_ca_fu_998_p1 : ret_V_21_2_1_fu_1028_p2);

assign p_2_2_fu_2240_p3 = ((tmp_195_fu_2232_p3[0:0] === 1'b1) ? 12'd0 : tmp_194_fu_2228_p1);

assign p_2_3_57_fu_2336_p3 = ((tmp_201_fu_2328_p3[0:0] === 1'b1) ? 12'd0 : tmp_200_fu_2324_p1);

assign p_2_3_fu_1126_p3 = ((tmp_89_2_3_fu_1114_p2[0:0] === 1'b1) ? p_Result_82_2_3_ca_fu_1090_p1 : ret_V_21_2_3_fu_1120_p2);

assign p_2_53_fu_2048_p3 = ((tmp_183_fu_2040_p3[0:0] === 1'b1) ? 12'd0 : tmp_182_fu_2036_p1);

assign p_2_fu_942_p3 = ((tmp_89_2_fu_930_p2[0:0] === 1'b1) ? p_Result_82_2_cast_fu_906_p1 : ret_V_21_2_fu_936_p2);

assign p_3_0_1_fu_1442_p3 = ((tmp_111_reg_2503[0:0] === 1'b1) ? 15'd0 : index_0_1_cast_reg_2498);

assign p_3_0_2_fu_1481_p3 = ((tmp_117_reg_2513[0:0] === 1'b1) ? 15'd0 : index_0_2_cast_reg_2508);

assign p_3_0_3_fu_1520_p3 = ((tmp_123_reg_2523[0:0] === 1'b1) ? 15'd0 : index_0_3_cast_reg_2518);

assign p_3_1_2_fu_1598_p3 = ((tmp_135_reg_2543[0:0] === 1'b1) ? 15'd0 : index_116_2_cast_reg_2538);

assign p_3_1_3_fu_1637_p3 = ((tmp_141_reg_2553[0:0] === 1'b1) ? 15'd0 : index_116_3_cast_reg_2548);

assign p_3_1_50_fu_1310_p3 = ((tmp_89_3_1_fu_1298_p2[0:0] === 1'b1) ? p_Result_82_3_1_ca_fu_1274_p1 : ret_V_21_3_1_fu_1304_p2);

assign p_3_1_fu_1559_p3 = ((tmp_129_reg_2533[0:0] === 1'b1) ? 15'd0 : index_cast_reg_2528);

assign p_3_2_1_fu_1715_p3 = ((tmp_153_reg_2573[0:0] === 1'b1) ? 15'd0 : index_2_1_cast_reg_2568);

assign p_3_2_3_fu_1754_p3 = ((tmp_159_reg_2583[0:0] === 1'b1) ? 15'd0 : index_2_3_cast_reg_2578);

assign p_3_2_51_fu_1402_p3 = ((tmp_89_3_2_fu_1390_p2[0:0] === 1'b1) ? p_Result_82_3_2_ca_fu_1366_p1 : ret_V_21_3_2_fu_1396_p2);

assign p_3_2_fu_1676_p3 = ((tmp_147_reg_2563[0:0] === 1'b1) ? 15'd0 : index_2_cast_reg_2558);

assign p_3_3_1_fu_1832_p3 = ((tmp_171_reg_2603[0:0] === 1'b1) ? 15'd0 : index_3_1_cast_reg_2598);

assign p_3_3_2_fu_1871_p3 = ((tmp_177_reg_2613[0:0] === 1'b1) ? 15'd0 : index_3_2_cast_reg_2608);

assign p_3_3_fu_1793_p3 = ((tmp_165_reg_2593[0:0] === 1'b1) ? 15'd0 : index_3_cast_reg_2588);

assign p_3_fu_1218_p3 = ((tmp_89_3_fu_1206_p2[0:0] === 1'b1) ? p_Result_82_3_cast_fu_1182_p1 : ret_V_21_3_fu_1212_p2);

assign p_4_1_fu_2124_p3 = ((tmp_186_fu_2084_p3[0:0] === 1'b1) ? p_1_1_fu_2116_p3 : p_Result_1_cast_fu_2080_p1);

assign p_4_2_fu_2220_p3 = ((tmp_192_fu_2180_p3[0:0] === 1'b1) ? p_1_2_55_fu_2212_p3 : p_Result_2_cast_fu_2176_p1);

assign p_4_3_fu_2316_p3 = ((tmp_198_fu_2276_p3[0:0] === 1'b1) ? p_1_3_56_fu_2308_p3 : p_Result_3_cast_fu_2272_p1);

assign p_4_fu_2028_p3 = ((tmp_180_fu_1988_p3[0:0] === 1'b1) ? p_1_52_fu_2020_p3 : p_Result_cast_fu_1984_p1);

assign p_5_0_1_fu_390_p3 = ((tmp_106_fu_350_p3[0:0] === 1'b1) ? p_0_1_fu_382_p3 : p_Result_82_0_1_ca_fu_346_p1);

assign p_5_0_2_fu_486_p3 = ((tmp_114_fu_446_p3[0:0] === 1'b1) ? p_0_2_fu_478_p3 : p_Result_82_0_2_ca_fu_442_p1);

assign p_5_0_3_fu_582_p3 = ((tmp_120_fu_542_p3[0:0] === 1'b1) ? p_0_3_fu_574_p3 : p_Result_82_0_3_ca_fu_538_p1);

assign p_5_1_2_fu_766_p3 = ((tmp_132_fu_726_p3[0:0] === 1'b1) ? p_1_2_fu_758_p3 : p_Result_82_1_2_ca_fu_722_p1);

assign p_5_1_3_fu_858_p3 = ((tmp_138_fu_818_p3[0:0] === 1'b1) ? p_1_3_fu_850_p3 : p_Result_82_1_3_ca_fu_814_p1);

assign p_5_1_fu_674_p3 = ((tmp_126_fu_634_p3[0:0] === 1'b1) ? p_1_fu_666_p3 : p_Result_82_1_cast_fu_630_p1);

assign p_5_2_1_fu_1042_p3 = ((tmp_150_fu_1002_p3[0:0] === 1'b1) ? p_2_1_fu_1034_p3 : p_Result_82_2_1_ca_fu_998_p1);

assign p_5_2_3_fu_1134_p3 = ((tmp_156_fu_1094_p3[0:0] === 1'b1) ? p_2_3_fu_1126_p3 : p_Result_82_2_3_ca_fu_1090_p1);

assign p_5_2_fu_950_p3 = ((tmp_144_fu_910_p3[0:0] === 1'b1) ? p_2_fu_942_p3 : p_Result_82_2_cast_fu_906_p1);

assign p_5_3_1_fu_1318_p3 = ((tmp_168_fu_1278_p3[0:0] === 1'b1) ? p_3_1_50_fu_1310_p3 : p_Result_82_3_1_ca_fu_1274_p1);

assign p_5_3_2_fu_1410_p3 = ((tmp_174_fu_1370_p3[0:0] === 1'b1) ? p_3_2_51_fu_1402_p3 : p_Result_82_3_2_ca_fu_1366_p1);

assign p_5_3_fu_1226_p3 = ((tmp_162_fu_1186_p3[0:0] === 1'b1) ? p_3_fu_1218_p3 : p_Result_82_3_cast_fu_1182_p1);

assign p_Result_1_cast_fu_2080_p1 = $signed(tmp_86_fu_2070_p4);

assign p_Result_2_cast_fu_2176_p1 = $signed(tmp_87_fu_2166_p4);

assign p_Result_3_cast_fu_2272_p1 = $signed(tmp_88_fu_2262_p4);

assign p_Result_4_fu_2000_p3 = {{tmp_181_fu_1996_p1}, {4'd0}};

assign p_Result_81_1_fu_2096_p3 = {{tmp_187_fu_2092_p1}, {4'd0}};

assign p_Result_81_2_fu_2192_p3 = {{tmp_193_fu_2188_p1}, {4'd0}};

assign p_Result_81_3_fu_2288_p3 = {{tmp_199_fu_2284_p1}, {4'd0}};

assign p_Result_82_0_1_ca_fu_346_p1 = $signed(tmp_s_fu_336_p4);

assign p_Result_82_0_2_ca_fu_442_p1 = $signed(tmp_66_fu_432_p4);

assign p_Result_82_0_3_ca_fu_538_p1 = $signed(tmp_69_fu_528_p4);

assign p_Result_82_1_2_ca_fu_722_p1 = $signed(tmp_75_fu_712_p4);

assign p_Result_82_1_3_ca_fu_814_p1 = $signed(tmp_76_fu_804_p4);

assign p_Result_82_1_cast_fu_630_p1 = $signed(tmp_72_fu_620_p4);

assign p_Result_82_2_1_ca_fu_998_p1 = $signed(tmp_79_fu_988_p4);

assign p_Result_82_2_3_ca_fu_1090_p1 = $signed(tmp_80_fu_1080_p4);

assign p_Result_82_2_cast_fu_906_p1 = $signed(tmp_78_fu_896_p4);

assign p_Result_82_3_1_ca_fu_1274_p1 = $signed(tmp_82_fu_1264_p4);

assign p_Result_82_3_2_ca_fu_1366_p1 = $signed(tmp_83_fu_1356_p4);

assign p_Result_82_3_cast_fu_1182_p1 = $signed(tmp_81_fu_1172_p4);

assign p_Result_84_0_1_fu_362_p3 = {{tmp_108_fu_358_p1}, {6'd0}};

assign p_Result_84_0_2_fu_458_p3 = {{tmp_115_fu_454_p1}, {6'd0}};

assign p_Result_84_0_3_fu_554_p3 = {{tmp_121_fu_550_p1}, {6'd0}};

assign p_Result_84_1_2_fu_738_p3 = {{tmp_133_fu_734_p1}, {6'd0}};

assign p_Result_84_1_3_fu_830_p3 = {{tmp_139_fu_826_p1}, {6'd0}};

assign p_Result_84_1_fu_646_p3 = {{tmp_127_fu_642_p1}, {6'd0}};

assign p_Result_84_2_1_fu_1014_p3 = {{tmp_151_fu_1010_p1}, {6'd0}};

assign p_Result_84_2_3_fu_1106_p3 = {{tmp_157_fu_1102_p1}, {6'd0}};

assign p_Result_84_2_fu_922_p3 = {{tmp_145_fu_918_p1}, {6'd0}};

assign p_Result_84_3_1_fu_1290_p3 = {{tmp_169_fu_1286_p1}, {6'd0}};

assign p_Result_84_3_2_fu_1382_p3 = {{tmp_175_fu_1378_p1}, {6'd0}};

assign p_Result_84_3_fu_1198_p3 = {{tmp_163_fu_1194_p1}, {6'd0}};

assign p_Result_cast_fu_1984_p1 = $signed(tmp_84_fu_1974_p4);

assign p_Val2_63_0_3_fu_1939_p2 = (tmp2_reg_2683 + tmp3_fu_1934_p2);

assign p_Val2_63_1_3_fu_1949_p2 = (tmp5_reg_2693 + tmp6_fu_1944_p2);

assign p_Val2_63_2_3_fu_1959_p2 = (tmp8_reg_2703 + tmp9_fu_1954_p2);

assign p_Val2_63_3_3_fu_1969_p2 = (tmp11_reg_2713 + tmp12_fu_1964_p2);

assign r_V_0_1_fu_330_p2 = ($signed(tmp_79_0_1_fu_322_p1) - $signed(tmp_80_0_1_fu_326_p1));

assign r_V_0_2_fu_426_p2 = ($signed(tmp_79_0_2_fu_422_p1) - $signed(tmp_80_0_1_fu_326_p1));

assign r_V_0_3_fu_522_p2 = ($signed(tmp_79_0_3_fu_518_p1) - $signed(tmp_80_0_1_fu_326_p1));

assign r_V_1_2_fu_706_p2 = ($signed(tmp_79_0_2_fu_422_p1) - $signed(tmp_79_0_1_fu_322_p1));

assign r_V_1_3_fu_798_p2 = ($signed(tmp_79_0_3_fu_518_p1) - $signed(tmp_79_0_1_fu_322_p1));

assign r_V_1_fu_614_p2 = ($signed(tmp_80_0_1_fu_326_p1) - $signed(tmp_79_0_1_fu_322_p1));

assign r_V_2_1_fu_982_p2 = ($signed(tmp_79_0_1_fu_322_p1) - $signed(tmp_79_0_2_fu_422_p1));

assign r_V_2_3_fu_1074_p2 = ($signed(tmp_79_0_3_fu_518_p1) - $signed(tmp_79_0_2_fu_422_p1));

assign r_V_2_fu_890_p2 = ($signed(tmp_80_0_1_fu_326_p1) - $signed(tmp_79_0_2_fu_422_p1));

assign r_V_3_1_fu_1258_p2 = ($signed(tmp_79_0_1_fu_322_p1) - $signed(tmp_79_0_3_fu_518_p1));

assign r_V_3_2_fu_1350_p2 = ($signed(tmp_79_0_2_fu_422_p1) - $signed(tmp_79_0_3_fu_518_p1));

assign r_V_3_fu_1166_p2 = ($signed(tmp_80_0_1_fu_326_p1) - $signed(tmp_79_0_3_fu_518_p1));

assign res_0_V_write_assig_1_fu_2434_p1 = res_0_V_write_assig_fu_2426_p3;

assign res_0_V_write_assig_fu_2426_p3 = {{invert_table5_q0}, {14'd0}};

assign res_1_V_write_assig_1_fu_2446_p1 = res_1_V_write_assig_fu_2438_p3;

assign res_1_V_write_assig_fu_2438_p3 = {{invert_table5_q1}, {14'd0}};

assign res_2_V_write_assig_1_fu_2458_p1 = res_2_V_write_assig_fu_2450_p3;

assign res_2_V_write_assig_fu_2450_p3 = {{invert_table5_q2}, {14'd0}};

assign res_3_V_write_assig_1_fu_2470_p1 = res_3_V_write_assig_fu_2462_p3;

assign res_3_V_write_assig_fu_2462_p3 = {{invert_table5_q3}, {14'd0}};

assign ret_V_19_1_fu_2110_p2 = ($signed(13'd1) + $signed(p_Result_1_cast_fu_2080_p1));

assign ret_V_19_2_fu_2206_p2 = ($signed(13'd1) + $signed(p_Result_2_cast_fu_2176_p1));

assign ret_V_19_3_fu_2302_p2 = ($signed(13'd1) + $signed(p_Result_3_cast_fu_2272_p1));

assign ret_V_21_0_1_fu_376_p2 = ($signed(16'd1) + $signed(p_Result_82_0_1_ca_fu_346_p1));

assign ret_V_21_0_2_fu_472_p2 = ($signed(16'd1) + $signed(p_Result_82_0_2_ca_fu_442_p1));

assign ret_V_21_0_3_fu_568_p2 = ($signed(16'd1) + $signed(p_Result_82_0_3_ca_fu_538_p1));

assign ret_V_21_1_2_fu_752_p2 = ($signed(16'd1) + $signed(p_Result_82_1_2_ca_fu_722_p1));

assign ret_V_21_1_3_fu_844_p2 = ($signed(16'd1) + $signed(p_Result_82_1_3_ca_fu_814_p1));

assign ret_V_21_1_fu_660_p2 = ($signed(16'd1) + $signed(p_Result_82_1_cast_fu_630_p1));

assign ret_V_21_2_1_fu_1028_p2 = ($signed(16'd1) + $signed(p_Result_82_2_1_ca_fu_998_p1));

assign ret_V_21_2_3_fu_1120_p2 = ($signed(16'd1) + $signed(p_Result_82_2_3_ca_fu_1090_p1));

assign ret_V_21_2_fu_936_p2 = ($signed(16'd1) + $signed(p_Result_82_2_cast_fu_906_p1));

assign ret_V_21_3_1_fu_1304_p2 = ($signed(16'd1) + $signed(p_Result_82_3_1_ca_fu_1274_p1));

assign ret_V_21_3_2_fu_1396_p2 = ($signed(16'd1) + $signed(p_Result_82_3_2_ca_fu_1366_p1));

assign ret_V_21_3_fu_1212_p2 = ($signed(16'd1) + $signed(p_Result_82_3_cast_fu_1182_p1));

assign ret_V_s_fu_2014_p2 = ($signed(13'd1) + $signed(p_Result_cast_fu_1984_p1));

assign tmp11_fu_1928_p2 = (exp_table4_q11 + exp_table4_q10);

assign tmp12_fu_1964_p2 = (18'd1024 + exp_table4_load_9_reg_2708);

assign tmp2_fu_1910_p2 = (exp_table4_q0 + exp_table4_q1);

assign tmp3_fu_1934_p2 = (18'd1024 + exp_table4_load_2_reg_2678);

assign tmp5_fu_1916_p2 = (exp_table4_q3 + exp_table4_q4);

assign tmp6_fu_1944_p2 = (18'd1024 + exp_table4_load_5_reg_2688);

assign tmp8_fu_1922_p2 = (exp_table4_q6 + exp_table4_q7);

assign tmp9_fu_1954_p2 = (18'd1024 + exp_table4_load_8_reg_2698);

assign tmp_106_fu_350_p3 = r_V_0_1_fu_330_p2[32'd32];

assign tmp_108_fu_358_p1 = r_V_0_1_fu_330_p2[17:0];

assign tmp_110_fu_398_p1 = p_5_0_1_fu_390_p3[14:0];

assign tmp_112_fu_1448_p1 = p_3_0_1_fu_1442_p3[9:0];

assign tmp_113_fu_1452_p4 = {{p_3_0_1_fu_1442_p3[14:10]}};

assign tmp_114_fu_446_p3 = r_V_0_2_fu_426_p2[32'd32];

assign tmp_115_fu_454_p1 = r_V_0_2_fu_426_p2[17:0];

assign tmp_116_fu_494_p1 = p_5_0_2_fu_486_p3[14:0];

assign tmp_118_fu_1487_p1 = p_3_0_2_fu_1481_p3[9:0];

assign tmp_119_fu_1491_p4 = {{p_3_0_2_fu_1481_p3[14:10]}};

assign tmp_120_fu_542_p3 = r_V_0_3_fu_522_p2[32'd32];

assign tmp_121_fu_550_p1 = r_V_0_3_fu_522_p2[17:0];

assign tmp_122_fu_590_p1 = p_5_0_3_fu_582_p3[14:0];

assign tmp_124_fu_1526_p1 = p_3_0_3_fu_1520_p3[9:0];

assign tmp_125_fu_1530_p4 = {{p_3_0_3_fu_1520_p3[14:10]}};

assign tmp_126_fu_634_p3 = r_V_1_fu_614_p2[32'd32];

assign tmp_127_fu_642_p1 = r_V_1_fu_614_p2[17:0];

assign tmp_128_fu_682_p1 = p_5_1_fu_674_p3[14:0];

assign tmp_130_fu_1565_p1 = p_3_1_fu_1559_p3[9:0];

assign tmp_131_fu_1569_p4 = {{p_3_1_fu_1559_p3[14:10]}};

assign tmp_132_fu_726_p3 = r_V_1_2_fu_706_p2[32'd32];

assign tmp_133_fu_734_p1 = r_V_1_2_fu_706_p2[17:0];

assign tmp_134_fu_774_p1 = p_5_1_2_fu_766_p3[14:0];

assign tmp_136_fu_1604_p1 = p_3_1_2_fu_1598_p3[9:0];

assign tmp_137_fu_1608_p4 = {{p_3_1_2_fu_1598_p3[14:10]}};

assign tmp_138_fu_818_p3 = r_V_1_3_fu_798_p2[32'd32];

assign tmp_139_fu_826_p1 = r_V_1_3_fu_798_p2[17:0];

assign tmp_140_fu_866_p1 = p_5_1_3_fu_858_p3[14:0];

assign tmp_142_fu_1643_p1 = p_3_1_3_fu_1637_p3[9:0];

assign tmp_143_fu_1647_p4 = {{p_3_1_3_fu_1637_p3[14:10]}};

assign tmp_144_fu_910_p3 = r_V_2_fu_890_p2[32'd32];

assign tmp_145_fu_918_p1 = r_V_2_fu_890_p2[17:0];

assign tmp_146_fu_958_p1 = p_5_2_fu_950_p3[14:0];

assign tmp_148_fu_1682_p1 = p_3_2_fu_1676_p3[9:0];

assign tmp_149_fu_1686_p4 = {{p_3_2_fu_1676_p3[14:10]}};

assign tmp_150_fu_1002_p3 = r_V_2_1_fu_982_p2[32'd32];

assign tmp_151_fu_1010_p1 = r_V_2_1_fu_982_p2[17:0];

assign tmp_152_fu_1050_p1 = p_5_2_1_fu_1042_p3[14:0];

assign tmp_154_fu_1721_p1 = p_3_2_1_fu_1715_p3[9:0];

assign tmp_155_fu_1725_p4 = {{p_3_2_1_fu_1715_p3[14:10]}};

assign tmp_156_fu_1094_p3 = r_V_2_3_fu_1074_p2[32'd32];

assign tmp_157_fu_1102_p1 = r_V_2_3_fu_1074_p2[17:0];

assign tmp_158_fu_1142_p1 = p_5_2_3_fu_1134_p3[14:0];

assign tmp_160_fu_1760_p1 = p_3_2_3_fu_1754_p3[9:0];

assign tmp_161_fu_1764_p4 = {{p_3_2_3_fu_1754_p3[14:10]}};

assign tmp_162_fu_1186_p3 = r_V_3_fu_1166_p2[32'd32];

assign tmp_163_fu_1194_p1 = r_V_3_fu_1166_p2[17:0];

assign tmp_164_fu_1234_p1 = p_5_3_fu_1226_p3[14:0];

assign tmp_166_fu_1799_p1 = p_3_3_fu_1793_p3[9:0];

assign tmp_167_fu_1803_p4 = {{p_3_3_fu_1793_p3[14:10]}};

assign tmp_168_fu_1278_p3 = r_V_3_1_fu_1258_p2[32'd32];

assign tmp_169_fu_1286_p1 = r_V_3_1_fu_1258_p2[17:0];

assign tmp_170_fu_1326_p1 = p_5_3_1_fu_1318_p3[14:0];

assign tmp_172_fu_1838_p1 = p_3_3_1_fu_1832_p3[9:0];

assign tmp_173_fu_1842_p4 = {{p_3_3_1_fu_1832_p3[14:10]}};

assign tmp_174_fu_1370_p3 = r_V_3_2_fu_1350_p2[32'd32];

assign tmp_175_fu_1378_p1 = r_V_3_2_fu_1350_p2[17:0];

assign tmp_176_fu_1418_p1 = p_5_3_2_fu_1410_p3[14:0];

assign tmp_178_fu_1877_p1 = p_3_3_2_fu_1871_p3[9:0];

assign tmp_179_fu_1881_p4 = {{p_3_3_2_fu_1871_p3[14:10]}};

assign tmp_180_fu_1988_p3 = p_Val2_63_0_3_fu_1939_p2[32'd17];

assign tmp_181_fu_1996_p1 = p_Val2_63_0_3_fu_1939_p2[5:0];

assign tmp_182_fu_2036_p1 = p_4_fu_2028_p3[11:0];

assign tmp_183_fu_2040_p3 = p_4_fu_2028_p3[32'd12];

assign tmp_184_fu_2056_p1 = p_2_53_fu_2048_p3[9:0];

assign tmp_186_fu_2084_p3 = p_Val2_63_1_3_fu_1949_p2[32'd17];

assign tmp_187_fu_2092_p1 = p_Val2_63_1_3_fu_1949_p2[5:0];

assign tmp_188_fu_2132_p1 = p_4_1_fu_2124_p3[11:0];

assign tmp_189_fu_2136_p3 = p_4_1_fu_2124_p3[32'd12];

assign tmp_190_fu_2152_p1 = p_2_1_54_fu_2144_p3[9:0];

assign tmp_192_fu_2180_p3 = p_Val2_63_2_3_fu_1959_p2[32'd17];

assign tmp_193_fu_2188_p1 = p_Val2_63_2_3_fu_1959_p2[5:0];

assign tmp_194_fu_2228_p1 = p_4_2_fu_2220_p3[11:0];

assign tmp_195_fu_2232_p3 = p_4_2_fu_2220_p3[32'd12];

assign tmp_196_fu_2248_p1 = p_2_2_fu_2240_p3[9:0];

assign tmp_198_fu_2276_p3 = p_Val2_63_3_3_fu_1969_p2[32'd17];

assign tmp_199_fu_2284_p1 = p_Val2_63_3_3_fu_1969_p2[5:0];

assign tmp_200_fu_2324_p1 = p_4_3_fu_2316_p3[11:0];

assign tmp_201_fu_2328_p3 = p_4_3_fu_2316_p3[32'd12];

assign tmp_202_fu_2344_p1 = p_2_3_57_fu_2336_p3[9:0];

assign tmp_66_fu_432_p4 = {{r_V_0_2_fu_426_p2[32:18]}};

assign tmp_69_fu_528_p4 = {{r_V_0_3_fu_522_p2[32:18]}};

assign tmp_72_fu_620_p4 = {{r_V_1_fu_614_p2[32:18]}};

assign tmp_75_fu_712_p4 = {{r_V_1_2_fu_706_p2[32:18]}};

assign tmp_76_fu_804_p4 = {{r_V_1_3_fu_798_p2[32:18]}};

assign tmp_77_1_fu_2104_p2 = ((p_Result_81_1_fu_2096_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_77_2_fu_2200_p2 = ((p_Result_81_2_fu_2192_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_77_3_fu_2296_p2 = ((p_Result_81_3_fu_2288_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_77_fu_2008_p2 = ((p_Result_4_fu_2000_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_78_fu_896_p4 = {{r_V_2_fu_890_p2[32:18]}};

assign tmp_79_0_1_fu_322_p1 = $signed(data_1_V_read);

assign tmp_79_0_2_fu_422_p1 = $signed(data_2_V_read);

assign tmp_79_0_3_fu_518_p1 = $signed(data_3_V_read);

assign tmp_79_fu_988_p4 = {{r_V_2_1_fu_982_p2[32:18]}};

assign tmp_80_0_1_fu_326_p1 = $signed(data_0_V_read);

assign tmp_80_fu_1080_p4 = {{r_V_2_3_fu_1074_p2[32:18]}};

assign tmp_81_fu_1172_p4 = {{r_V_3_fu_1166_p2[32:18]}};

assign tmp_82_fu_1264_p4 = {{r_V_3_1_fu_1258_p2[32:18]}};

assign tmp_83_fu_1356_p4 = {{r_V_3_2_fu_1350_p2[32:18]}};

assign tmp_84_fu_1974_p4 = {{p_Val2_63_0_3_fu_1939_p2[17:6]}};

assign tmp_85_fu_2370_p1 = exp_res_index_1_fu_2363_p3;

assign tmp_86_1_fu_2387_p1 = exp_res_index_1_1_fu_2380_p3;

assign tmp_86_2_fu_2404_p1 = exp_res_index_1_2_fu_2397_p3;

assign tmp_86_3_fu_2421_p1 = exp_res_index_1_3_fu_2414_p3;

assign tmp_86_fu_2070_p4 = {{p_Val2_63_1_3_fu_1949_p2[17:6]}};

assign tmp_87_fu_2166_p4 = {{p_Val2_63_2_3_fu_1959_p2[17:6]}};

assign tmp_88_fu_2262_p4 = {{p_Val2_63_3_3_fu_1969_p2[17:6]}};

assign tmp_89_0_1_fu_370_p2 = ((p_Result_84_0_1_fu_362_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_0_2_fu_466_p2 = ((p_Result_84_0_2_fu_458_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_0_3_fu_562_p2 = ((p_Result_84_0_3_fu_554_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_1_2_fu_746_p2 = ((p_Result_84_1_2_fu_738_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_1_3_fu_838_p2 = ((p_Result_84_1_3_fu_830_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_1_fu_654_p2 = ((p_Result_84_1_fu_646_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_2_1_fu_1022_p2 = ((p_Result_84_2_1_fu_1014_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_2_3_fu_1114_p2 = ((p_Result_84_2_3_fu_1106_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_2_fu_930_p2 = ((p_Result_84_2_fu_922_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_3_1_fu_1298_p2 = ((p_Result_84_3_1_fu_1290_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_3_2_fu_1390_p2 = ((p_Result_84_3_2_fu_1382_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_89_3_fu_1206_p2 = ((p_Result_84_3_fu_1198_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_92_0_1_fu_1476_p1 = index_1_0_1_fu_1468_p3;

assign tmp_92_0_2_fu_1515_p1 = index_1_0_2_fu_1507_p3;

assign tmp_92_0_3_fu_1554_p1 = index_1_0_3_fu_1546_p3;

assign tmp_92_1_2_fu_1632_p1 = index_1_1_2_fu_1624_p3;

assign tmp_92_1_3_fu_1671_p1 = index_1_1_3_fu_1663_p3;

assign tmp_92_1_fu_1593_p1 = index_1_1_fu_1585_p3;

assign tmp_92_2_1_fu_1749_p1 = index_1_2_1_fu_1741_p3;

assign tmp_92_2_3_fu_1788_p1 = index_1_2_3_fu_1780_p3;

assign tmp_92_2_fu_1710_p1 = index_1_2_fu_1702_p3;

assign tmp_92_3_1_fu_1866_p1 = index_1_3_1_fu_1858_p3;

assign tmp_92_3_2_fu_1905_p1 = index_1_3_2_fu_1897_p3;

assign tmp_92_3_fu_1827_p1 = index_1_3_fu_1819_p3;

assign tmp_s_fu_336_p4 = {{r_V_0_1_fu_330_p2[32:18]}};

endmodule //softmax
