// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module softmax (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_0_V_read;
input  [31:0] data_1_V_read;
input  [31:0] data_2_V_read;
input  [31:0] data_3_V_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] exp_table2_address0;
reg    exp_table2_ce0;
wire   [17:0] exp_table2_q0;
wire   [9:0] exp_table2_address1;
reg    exp_table2_ce1;
wire   [17:0] exp_table2_q1;
wire   [9:0] exp_table2_address2;
reg    exp_table2_ce2;
wire   [17:0] exp_table2_q2;
wire   [9:0] exp_table2_address3;
reg    exp_table2_ce3;
wire   [17:0] exp_table2_q3;
wire   [9:0] exp_table2_address4;
reg    exp_table2_ce4;
wire   [17:0] exp_table2_q4;
wire   [9:0] exp_table2_address5;
reg    exp_table2_ce5;
wire   [17:0] exp_table2_q5;
wire   [9:0] exp_table2_address6;
reg    exp_table2_ce6;
wire   [17:0] exp_table2_q6;
wire   [9:0] exp_table2_address7;
reg    exp_table2_ce7;
wire   [17:0] exp_table2_q7;
wire   [9:0] exp_table2_address8;
reg    exp_table2_ce8;
wire   [17:0] exp_table2_q8;
wire   [9:0] exp_table2_address9;
reg    exp_table2_ce9;
wire   [17:0] exp_table2_q9;
wire   [9:0] exp_table2_address10;
reg    exp_table2_ce10;
wire   [17:0] exp_table2_q10;
wire   [9:0] exp_table2_address11;
reg    exp_table2_ce11;
wire   [17:0] exp_table2_q11;
wire   [9:0] invert_table3_address0;
reg    invert_table3_ce0;
wire   [14:0] invert_table3_q0;
wire   [9:0] invert_table3_address1;
reg    invert_table3_ce1;
wire   [14:0] invert_table3_q1;
wire   [9:0] invert_table3_address2;
reg    invert_table3_ce2;
wire   [14:0] invert_table3_q2;
wire   [9:0] invert_table3_address3;
reg    invert_table3_ce3;
wire   [14:0] invert_table3_q3;
wire   [9:0] tmp_11_fu_430_p1;
reg   [9:0] tmp_11_reg_2498;
reg   [4:0] tmp_13_reg_2503;
wire   [9:0] tmp_23_fu_548_p1;
reg   [9:0] tmp_23_reg_2508;
reg   [4:0] tmp_25_reg_2513;
wire   [9:0] tmp_34_fu_666_p1;
reg   [9:0] tmp_34_reg_2518;
reg   [4:0] tmp_36_reg_2523;
wire   [9:0] tmp_41_fu_780_p1;
reg   [9:0] tmp_41_reg_2528;
reg   [4:0] tmp_42_reg_2533;
wire   [9:0] tmp_47_fu_894_p1;
reg   [9:0] tmp_47_reg_2538;
reg   [4:0] tmp_48_reg_2543;
wire   [9:0] tmp_53_fu_1008_p1;
reg   [9:0] tmp_53_reg_2548;
reg   [4:0] tmp_54_reg_2553;
wire   [9:0] tmp_59_fu_1122_p1;
reg   [9:0] tmp_59_reg_2558;
reg   [4:0] tmp_60_reg_2563;
wire   [9:0] tmp_65_fu_1236_p1;
reg   [9:0] tmp_65_reg_2568;
reg   [4:0] tmp_66_reg_2573;
wire   [9:0] tmp_71_fu_1350_p1;
reg   [9:0] tmp_71_reg_2578;
reg   [4:0] tmp_72_reg_2583;
wire   [9:0] tmp_77_fu_1464_p1;
reg   [9:0] tmp_77_reg_2588;
reg   [4:0] tmp_78_reg_2593;
wire   [9:0] tmp_83_fu_1578_p1;
reg   [9:0] tmp_83_reg_2598;
reg   [4:0] tmp_84_reg_2603;
wire   [9:0] tmp_89_fu_1692_p1;
reg   [9:0] tmp_89_reg_2608;
reg   [4:0] tmp_90_reg_2613;
reg   [17:0] exp_table2_load_2_reg_2678;
wire   [17:0] tmp2_fu_1910_p2;
reg   [17:0] tmp2_reg_2683;
reg   [17:0] exp_table2_load_5_reg_2688;
wire   [17:0] tmp5_fu_1916_p2;
reg   [17:0] tmp5_reg_2693;
reg   [17:0] exp_table2_load_8_reg_2698;
wire   [17:0] tmp8_fu_1922_p2;
reg   [17:0] tmp8_reg_2703;
reg   [17:0] exp_table2_load_9_reg_2708;
wire   [17:0] tmp1_fu_1928_p2;
reg   [17:0] tmp1_reg_2713;
wire   [9:0] tmp_95_fu_2056_p1;
reg   [9:0] tmp_95_reg_2718;
wire   [0:0] icmp12_fu_2070_p2;
reg   [0:0] icmp12_reg_2723;
wire   [9:0] tmp_101_fu_2158_p1;
reg   [9:0] tmp_101_reg_2728;
wire   [0:0] icmp13_fu_2172_p2;
reg   [0:0] icmp13_reg_2733;
wire   [9:0] tmp_107_fu_2260_p1;
reg   [9:0] tmp_107_reg_2738;
wire   [0:0] icmp14_fu_2274_p2;
reg   [0:0] icmp14_reg_2743;
wire   [9:0] tmp_113_fu_2362_p1;
reg   [9:0] tmp_113_reg_2748;
wire   [0:0] icmp15_fu_2376_p2;
reg   [0:0] icmp15_reg_2753;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] tmp_25_0_1_fu_1718_p1;
wire   [63:0] tmp_25_0_2_fu_1735_p1;
wire   [63:0] tmp_25_0_3_fu_1752_p1;
wire   [63:0] tmp_25_1_fu_1769_p1;
wire   [63:0] tmp_25_1_2_fu_1786_p1;
wire   [63:0] tmp_25_1_3_fu_1803_p1;
wire   [63:0] tmp_25_2_fu_1820_p1;
wire   [63:0] tmp_25_2_1_fu_1837_p1;
wire   [63:0] tmp_25_2_3_fu_1854_p1;
wire   [63:0] tmp_25_3_fu_1871_p1;
wire   [63:0] tmp_25_3_1_fu_1888_p1;
wire   [63:0] tmp_25_3_2_fu_1905_p1;
wire   [63:0] tmp_26_fu_2388_p1;
wire   [63:0] tmp_19_1_fu_2399_p1;
wire   [63:0] tmp_19_2_fu_2410_p1;
wire   [63:0] tmp_19_3_fu_2421_p1;
wire  signed [32:0] tmp_12_0_1_fu_322_p1;
wire  signed [32:0] tmp_13_0_1_fu_326_p1;
wire   [32:0] r_V_0_1_fu_330_p2;
wire   [14:0] tmp_1_fu_336_p4;
wire   [17:0] tmp_4_fu_358_p1;
wire   [23:0] p_Result_5_0_1_fu_362_p3;
wire  signed [15:0] p_Result_3_0_1_cas_fu_346_p1;
wire   [0:0] tmp_22_0_1_fu_370_p2;
wire   [15:0] ret_V_3_0_1_fu_376_p2;
wire   [0:0] tmp_2_fu_350_p3;
wire   [15:0] p_0_1_fu_382_p3;
wire   [15:0] p_5_0_1_fu_390_p3;
wire   [14:0] tmp_6_fu_398_p1;
wire   [15:0] index_0_1_fu_402_p2;
wire   [0:0] tmp_8_fu_414_p3;
wire   [14:0] index_0_1_cast_fu_408_p2;
wire   [14:0] p_3_0_1_fu_422_p3;
wire  signed [32:0] tmp_12_0_2_fu_444_p1;
wire   [32:0] r_V_0_2_fu_448_p2;
wire   [14:0] tmp_3_fu_454_p4;
wire   [17:0] tmp_17_fu_476_p1;
wire   [23:0] p_Result_5_0_2_fu_480_p3;
wire  signed [15:0] p_Result_3_0_2_cas_fu_464_p1;
wire   [0:0] tmp_22_0_2_fu_488_p2;
wire   [15:0] ret_V_3_0_2_fu_494_p2;
wire   [0:0] tmp_15_fu_468_p3;
wire   [15:0] p_0_2_fu_500_p3;
wire   [15:0] p_5_0_2_fu_508_p3;
wire   [14:0] tmp_19_fu_516_p1;
wire   [15:0] index_0_2_fu_520_p2;
wire   [0:0] tmp_21_fu_532_p3;
wire   [14:0] index_0_2_cast_fu_526_p2;
wire   [14:0] p_3_0_2_fu_540_p3;
wire  signed [32:0] tmp_12_0_3_fu_562_p1;
wire   [32:0] r_V_0_3_fu_566_p2;
wire   [14:0] tmp_5_fu_572_p4;
wire   [17:0] tmp_30_fu_594_p1;
wire   [23:0] p_Result_5_0_3_fu_598_p3;
wire  signed [15:0] p_Result_3_0_3_cas_fu_582_p1;
wire   [0:0] tmp_22_0_3_fu_606_p2;
wire   [15:0] ret_V_3_0_3_fu_612_p2;
wire   [0:0] tmp_28_fu_586_p3;
wire   [15:0] p_0_3_fu_618_p3;
wire   [15:0] p_5_0_3_fu_626_p3;
wire   [14:0] tmp_32_fu_634_p1;
wire   [15:0] index_0_3_fu_638_p2;
wire   [0:0] tmp_33_fu_650_p3;
wire   [14:0] index_0_3_cast_fu_644_p2;
wire   [14:0] p_3_0_3_fu_658_p3;
wire   [32:0] r_V_1_fu_680_p2;
wire   [14:0] tmp_7_fu_686_p4;
wire   [17:0] tmp_38_fu_708_p1;
wire   [23:0] p_Result_5_1_fu_712_p3;
wire  signed [15:0] p_Result_3_1_cast_fu_696_p1;
wire   [0:0] tmp_22_1_fu_720_p2;
wire   [15:0] ret_V_3_1_fu_726_p2;
wire   [0:0] tmp_37_fu_700_p3;
wire   [15:0] p_1_fu_732_p3;
wire   [15:0] p_5_1_fu_740_p3;
wire   [14:0] tmp_39_fu_748_p1;
wire   [15:0] index_s_fu_752_p2;
wire   [0:0] tmp_40_fu_764_p3;
wire   [14:0] index_cast_fu_758_p2;
wire   [14:0] p_3_1_fu_772_p3;
wire   [32:0] r_V_1_2_fu_794_p2;
wire   [14:0] tmp_9_fu_800_p4;
wire   [17:0] tmp_44_fu_822_p1;
wire   [23:0] p_Result_5_1_2_fu_826_p3;
wire  signed [15:0] p_Result_3_1_2_cas_fu_810_p1;
wire   [0:0] tmp_22_1_2_fu_834_p2;
wire   [15:0] ret_V_3_1_2_fu_840_p2;
wire   [0:0] tmp_43_fu_814_p3;
wire   [15:0] p_1_2_fu_846_p3;
wire   [15:0] p_5_1_2_fu_854_p3;
wire   [14:0] tmp_45_fu_862_p1;
wire   [15:0] index_119_2_fu_866_p2;
wire   [0:0] tmp_46_fu_878_p3;
wire   [14:0] index_119_2_cast_fu_872_p2;
wire   [14:0] p_3_1_2_fu_886_p3;
wire   [32:0] r_V_1_3_fu_908_p2;
wire   [14:0] tmp_s_fu_914_p4;
wire   [17:0] tmp_50_fu_936_p1;
wire   [23:0] p_Result_5_1_3_fu_940_p3;
wire  signed [15:0] p_Result_3_1_3_cas_fu_924_p1;
wire   [0:0] tmp_22_1_3_fu_948_p2;
wire   [15:0] ret_V_3_1_3_fu_954_p2;
wire   [0:0] tmp_49_fu_928_p3;
wire   [15:0] p_1_3_fu_960_p3;
wire   [15:0] p_5_1_3_fu_968_p3;
wire   [14:0] tmp_51_fu_976_p1;
wire   [15:0] index_119_3_fu_980_p2;
wire   [0:0] tmp_52_fu_992_p3;
wire   [14:0] index_119_3_cast_fu_986_p2;
wire   [14:0] p_3_1_3_fu_1000_p3;
wire   [32:0] r_V_2_fu_1022_p2;
wire   [14:0] tmp_10_fu_1028_p4;
wire   [17:0] tmp_56_fu_1050_p1;
wire   [23:0] p_Result_5_2_fu_1054_p3;
wire  signed [15:0] p_Result_3_2_cast_fu_1038_p1;
wire   [0:0] tmp_22_2_fu_1062_p2;
wire   [15:0] ret_V_3_2_fu_1068_p2;
wire   [0:0] tmp_55_fu_1042_p3;
wire   [15:0] p_2_fu_1074_p3;
wire   [15:0] p_5_2_fu_1082_p3;
wire   [14:0] tmp_57_fu_1090_p1;
wire   [15:0] index_2_fu_1094_p2;
wire   [0:0] tmp_58_fu_1106_p3;
wire   [14:0] index_2_cast_fu_1100_p2;
wire   [14:0] p_3_2_fu_1114_p3;
wire   [32:0] r_V_2_1_fu_1136_p2;
wire   [14:0] tmp_12_fu_1142_p4;
wire   [17:0] tmp_62_fu_1164_p1;
wire   [23:0] p_Result_5_2_1_fu_1168_p3;
wire  signed [15:0] p_Result_3_2_1_cas_fu_1152_p1;
wire   [0:0] tmp_22_2_1_fu_1176_p2;
wire   [15:0] ret_V_3_2_1_fu_1182_p2;
wire   [0:0] tmp_61_fu_1156_p3;
wire   [15:0] p_2_1_fu_1188_p3;
wire   [15:0] p_5_2_1_fu_1196_p3;
wire   [14:0] tmp_63_fu_1204_p1;
wire   [15:0] index_2_1_fu_1208_p2;
wire   [0:0] tmp_64_fu_1220_p3;
wire   [14:0] index_2_1_cast_fu_1214_p2;
wire   [14:0] p_3_2_1_fu_1228_p3;
wire   [32:0] r_V_2_3_fu_1250_p2;
wire   [14:0] tmp_14_fu_1256_p4;
wire   [17:0] tmp_68_fu_1278_p1;
wire   [23:0] p_Result_5_2_3_fu_1282_p3;
wire  signed [15:0] p_Result_3_2_3_cas_fu_1266_p1;
wire   [0:0] tmp_22_2_3_fu_1290_p2;
wire   [15:0] ret_V_3_2_3_fu_1296_p2;
wire   [0:0] tmp_67_fu_1270_p3;
wire   [15:0] p_2_3_fu_1302_p3;
wire   [15:0] p_5_2_3_fu_1310_p3;
wire   [14:0] tmp_69_fu_1318_p1;
wire   [15:0] index_2_3_fu_1322_p2;
wire   [0:0] tmp_70_fu_1334_p3;
wire   [14:0] index_2_3_cast_fu_1328_p2;
wire   [14:0] p_3_2_3_fu_1342_p3;
wire   [32:0] r_V_3_fu_1364_p2;
wire   [14:0] tmp_16_fu_1370_p4;
wire   [17:0] tmp_74_fu_1392_p1;
wire   [23:0] p_Result_5_3_fu_1396_p3;
wire  signed [15:0] p_Result_3_3_cast_fu_1380_p1;
wire   [0:0] tmp_22_3_fu_1404_p2;
wire   [15:0] ret_V_3_3_fu_1410_p2;
wire   [0:0] tmp_73_fu_1384_p3;
wire   [15:0] p_3_fu_1416_p3;
wire   [15:0] p_5_3_fu_1424_p3;
wire   [14:0] tmp_75_fu_1432_p1;
wire   [15:0] index_3_fu_1436_p2;
wire   [0:0] tmp_76_fu_1448_p3;
wire   [14:0] index_3_cast_fu_1442_p2;
wire   [14:0] p_3_3_fu_1456_p3;
wire   [32:0] r_V_3_1_fu_1478_p2;
wire   [14:0] tmp_18_fu_1484_p4;
wire   [17:0] tmp_80_fu_1506_p1;
wire   [23:0] p_Result_5_3_1_fu_1510_p3;
wire  signed [15:0] p_Result_3_3_1_cas_fu_1494_p1;
wire   [0:0] tmp_22_3_1_fu_1518_p2;
wire   [15:0] ret_V_3_3_1_fu_1524_p2;
wire   [0:0] tmp_79_fu_1498_p3;
wire   [15:0] p_3_1_18_fu_1530_p3;
wire   [15:0] p_5_3_1_fu_1538_p3;
wire   [14:0] tmp_81_fu_1546_p1;
wire   [15:0] index_3_1_fu_1550_p2;
wire   [0:0] tmp_82_fu_1562_p3;
wire   [14:0] index_3_1_cast_fu_1556_p2;
wire   [14:0] p_3_3_1_fu_1570_p3;
wire   [32:0] r_V_3_2_fu_1592_p2;
wire   [14:0] tmp_20_fu_1598_p4;
wire   [17:0] tmp_86_fu_1620_p1;
wire   [23:0] p_Result_5_3_2_fu_1624_p3;
wire  signed [15:0] p_Result_3_3_2_cas_fu_1608_p1;
wire   [0:0] tmp_22_3_2_fu_1632_p2;
wire   [15:0] ret_V_3_3_2_fu_1638_p2;
wire   [0:0] tmp_85_fu_1612_p3;
wire   [15:0] p_3_2_19_fu_1644_p3;
wire   [15:0] p_5_3_2_fu_1652_p3;
wire   [14:0] tmp_87_fu_1660_p1;
wire   [15:0] index_3_2_fu_1664_p2;
wire   [0:0] tmp_88_fu_1676_p3;
wire   [14:0] index_3_2_cast_fu_1670_p2;
wire   [14:0] p_3_3_2_fu_1684_p3;
wire   [0:0] icmp_fu_1706_p2;
wire   [9:0] index_1_0_1_fu_1711_p3;
wire   [0:0] icmp1_fu_1723_p2;
wire   [9:0] index_1_0_2_fu_1728_p3;
wire   [0:0] icmp2_fu_1740_p2;
wire   [9:0] index_1_0_3_fu_1745_p3;
wire   [0:0] icmp3_fu_1757_p2;
wire   [9:0] index_1_1_fu_1762_p3;
wire   [0:0] icmp4_fu_1774_p2;
wire   [9:0] index_1_1_2_fu_1779_p3;
wire   [0:0] icmp5_fu_1791_p2;
wire   [9:0] index_1_1_3_fu_1796_p3;
wire   [0:0] icmp6_fu_1808_p2;
wire   [9:0] index_1_2_fu_1813_p3;
wire   [0:0] icmp7_fu_1825_p2;
wire   [9:0] index_1_2_1_fu_1830_p3;
wire   [0:0] icmp8_fu_1842_p2;
wire   [9:0] index_1_2_3_fu_1847_p3;
wire   [0:0] icmp9_fu_1859_p2;
wire   [9:0] index_1_3_fu_1864_p3;
wire   [0:0] icmp10_fu_1876_p2;
wire   [9:0] index_1_3_1_fu_1881_p3;
wire   [0:0] icmp11_fu_1893_p2;
wire   [9:0] index_1_3_2_fu_1898_p3;
wire   [17:0] tmp3_fu_1934_p2;
wire   [17:0] tmp6_fu_1944_p2;
wire   [17:0] tmp9_fu_1954_p2;
wire   [17:0] tmp4_fu_1964_p2;
wire   [17:0] p_Val2_7_0_3_fu_1939_p2;
wire   [11:0] tmp_22_fu_1974_p4;
wire   [5:0] tmp_92_fu_1996_p1;
wire   [9:0] p_Result_2_fu_2000_p3;
wire  signed [12:0] p_Result_cast_fu_1984_p1;
wire   [0:0] tmp_24_fu_2008_p2;
wire   [12:0] ret_V_1_fu_2014_p2;
wire   [0:0] tmp_91_fu_1988_p3;
wire   [12:0] p_1_20_fu_2020_p3;
wire   [12:0] p_4_fu_2028_p3;
wire   [0:0] tmp_94_fu_2040_p3;
wire   [11:0] tmp_93_fu_2036_p1;
wire   [11:0] p_2_21_fu_2048_p3;
wire   [1:0] tmp_96_fu_2060_p4;
wire   [17:0] p_Val2_7_1_3_fu_1949_p2;
wire   [11:0] tmp_27_fu_2076_p4;
wire   [5:0] tmp_98_fu_2098_p1;
wire   [9:0] p_Result_2_1_fu_2102_p3;
wire  signed [12:0] p_Result_cast_22_fu_2086_p1;
wire   [0:0] tmp_10_1_fu_2110_p2;
wire   [12:0] ret_V_1_1_fu_2116_p2;
wire   [0:0] tmp_97_fu_2090_p3;
wire   [12:0] p_1_1_fu_2122_p3;
wire   [12:0] p_4_1_fu_2130_p3;
wire   [0:0] tmp_100_fu_2142_p3;
wire   [11:0] tmp_99_fu_2138_p1;
wire   [11:0] p_2_1_23_fu_2150_p3;
wire   [1:0] tmp_102_fu_2162_p4;
wire   [17:0] p_Val2_7_2_3_fu_1959_p2;
wire   [11:0] tmp_29_fu_2178_p4;
wire   [5:0] tmp_104_fu_2200_p1;
wire   [9:0] p_Result_2_2_fu_2204_p3;
wire  signed [12:0] p_Result_4_cast_fu_2188_p1;
wire   [0:0] tmp_10_2_fu_2212_p2;
wire   [12:0] ret_V_1_2_fu_2218_p2;
wire   [0:0] tmp_103_fu_2192_p3;
wire   [12:0] p_1_2_24_fu_2224_p3;
wire   [12:0] p_4_2_fu_2232_p3;
wire   [0:0] tmp_106_fu_2244_p3;
wire   [11:0] tmp_105_fu_2240_p1;
wire   [11:0] p_2_2_fu_2252_p3;
wire   [1:0] tmp_108_fu_2264_p4;
wire   [17:0] p_Val2_7_3_3_fu_1969_p2;
wire   [11:0] tmp_31_fu_2280_p4;
wire   [5:0] tmp_110_fu_2302_p1;
wire   [9:0] p_Result_2_3_fu_2306_p3;
wire  signed [12:0] p_Result_3_cast_fu_2290_p1;
wire   [0:0] tmp_10_3_fu_2314_p2;
wire   [12:0] ret_V_1_3_fu_2320_p2;
wire   [0:0] tmp_109_fu_2294_p3;
wire   [12:0] p_1_3_25_fu_2326_p3;
wire   [12:0] p_4_3_fu_2334_p3;
wire   [0:0] tmp_112_fu_2346_p3;
wire   [11:0] tmp_111_fu_2342_p1;
wire   [11:0] p_2_3_26_fu_2354_p3;
wire   [1:0] tmp_114_fu_2366_p4;
wire   [9:0] exp_res_index_1_fu_2382_p3;
wire   [9:0] exp_res_index_1_1_fu_2393_p3;
wire   [9:0] exp_res_index_1_2_fu_2404_p3;
wire   [9:0] exp_res_index_1_3_fu_2415_p3;
wire   [28:0] res_0_V_write_assig_fu_2426_p3;
wire   [28:0] res_1_V_write_assig_fu_2438_p3;
wire   [28:0] res_2_V_write_assig_fu_2450_p3;
wire   [28:0] res_3_V_write_assig_fu_2462_p3;
wire   [31:0] res_0_V_write_assig_1_fu_2434_p1;
wire   [31:0] res_1_V_write_assig_1_fu_2446_p1;
wire   [31:0] res_2_V_write_assig_1_fu_2458_p1;
wire   [31:0] res_3_V_write_assig_1_fu_2470_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

softmax_exp_table2 #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table2_address0),
    .ce0(exp_table2_ce0),
    .q0(exp_table2_q0),
    .address1(exp_table2_address1),
    .ce1(exp_table2_ce1),
    .q1(exp_table2_q1),
    .address2(exp_table2_address2),
    .ce2(exp_table2_ce2),
    .q2(exp_table2_q2),
    .address3(exp_table2_address3),
    .ce3(exp_table2_ce3),
    .q3(exp_table2_q3),
    .address4(exp_table2_address4),
    .ce4(exp_table2_ce4),
    .q4(exp_table2_q4),
    .address5(exp_table2_address5),
    .ce5(exp_table2_ce5),
    .q5(exp_table2_q5),
    .address6(exp_table2_address6),
    .ce6(exp_table2_ce6),
    .q6(exp_table2_q6),
    .address7(exp_table2_address7),
    .ce7(exp_table2_ce7),
    .q7(exp_table2_q7),
    .address8(exp_table2_address8),
    .ce8(exp_table2_ce8),
    .q8(exp_table2_q8),
    .address9(exp_table2_address9),
    .ce9(exp_table2_ce9),
    .q9(exp_table2_q9),
    .address10(exp_table2_address10),
    .ce10(exp_table2_ce10),
    .q10(exp_table2_q10),
    .address11(exp_table2_address11),
    .ce11(exp_table2_ce11),
    .q11(exp_table2_q11)
);

softmax_invert_tabkb #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table3_address0),
    .ce0(invert_table3_ce0),
    .q0(invert_table3_q0),
    .address1(invert_table3_address1),
    .ce1(invert_table3_ce1),
    .q1(invert_table3_q1),
    .address2(invert_table3_address2),
    .ce2(invert_table3_ce2),
    .q2(invert_table3_q2),
    .address3(invert_table3_address3),
    .ce3(invert_table3_ce3),
    .q3(invert_table3_q3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        exp_table2_load_2_reg_2678 <= exp_table2_q2;
        exp_table2_load_5_reg_2688 <= exp_table2_q5;
        exp_table2_load_8_reg_2698 <= exp_table2_q8;
        exp_table2_load_9_reg_2708 <= exp_table2_q9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp12_reg_2723 <= icmp12_fu_2070_p2;
        icmp13_reg_2733 <= icmp13_fu_2172_p2;
        icmp14_reg_2743 <= icmp14_fu_2274_p2;
        icmp15_reg_2753 <= icmp15_fu_2376_p2;
        tmp1_reg_2713 <= tmp1_fu_1928_p2;
        tmp2_reg_2683 <= tmp2_fu_1910_p2;
        tmp5_reg_2693 <= tmp5_fu_1916_p2;
        tmp8_reg_2703 <= tmp8_fu_1922_p2;
        tmp_101_reg_2728 <= tmp_101_fu_2158_p1;
        tmp_107_reg_2738 <= tmp_107_fu_2260_p1;
        tmp_113_reg_2748 <= tmp_113_fu_2362_p1;
        tmp_95_reg_2718 <= tmp_95_fu_2056_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_11_reg_2498 <= tmp_11_fu_430_p1;
        tmp_13_reg_2503 <= {{p_3_0_1_fu_422_p3[14:10]}};
        tmp_23_reg_2508 <= tmp_23_fu_548_p1;
        tmp_25_reg_2513 <= {{p_3_0_2_fu_540_p3[14:10]}};
        tmp_34_reg_2518 <= tmp_34_fu_666_p1;
        tmp_36_reg_2523 <= {{p_3_0_3_fu_658_p3[14:10]}};
        tmp_41_reg_2528 <= tmp_41_fu_780_p1;
        tmp_42_reg_2533 <= {{p_3_1_fu_772_p3[14:10]}};
        tmp_47_reg_2538 <= tmp_47_fu_894_p1;
        tmp_48_reg_2543 <= {{p_3_1_2_fu_886_p3[14:10]}};
        tmp_53_reg_2548 <= tmp_53_fu_1008_p1;
        tmp_54_reg_2553 <= {{p_3_1_3_fu_1000_p3[14:10]}};
        tmp_59_reg_2558 <= tmp_59_fu_1122_p1;
        tmp_60_reg_2563 <= {{p_3_2_fu_1114_p3[14:10]}};
        tmp_65_reg_2568 <= tmp_65_fu_1236_p1;
        tmp_66_reg_2573 <= {{p_3_2_1_fu_1228_p3[14:10]}};
        tmp_71_reg_2578 <= tmp_71_fu_1350_p1;
        tmp_72_reg_2583 <= {{p_3_2_3_fu_1342_p3[14:10]}};
        tmp_77_reg_2588 <= tmp_77_fu_1464_p1;
        tmp_78_reg_2593 <= {{p_3_3_fu_1456_p3[14:10]}};
        tmp_83_reg_2598 <= tmp_83_fu_1578_p1;
        tmp_84_reg_2603 <= {{p_3_3_1_fu_1570_p3[14:10]}};
        tmp_89_reg_2608 <= tmp_89_fu_1692_p1;
        tmp_90_reg_2613 <= {{p_3_3_2_fu_1684_p3[14:10]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce0 = 1'b1;
    end else begin
        exp_table2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce1 = 1'b1;
    end else begin
        exp_table2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce10 = 1'b1;
    end else begin
        exp_table2_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce11 = 1'b1;
    end else begin
        exp_table2_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce2 = 1'b1;
    end else begin
        exp_table2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce3 = 1'b1;
    end else begin
        exp_table2_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce4 = 1'b1;
    end else begin
        exp_table2_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce5 = 1'b1;
    end else begin
        exp_table2_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce6 = 1'b1;
    end else begin
        exp_table2_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce7 = 1'b1;
    end else begin
        exp_table2_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce8 = 1'b1;
    end else begin
        exp_table2_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table2_ce9 = 1'b1;
    end else begin
        exp_table2_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table3_ce0 = 1'b1;
    end else begin
        invert_table3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table3_ce1 = 1'b1;
    end else begin
        invert_table3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table3_ce2 = 1'b1;
    end else begin
        invert_table3_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        invert_table3_ce3 = 1'b1;
    end else begin
        invert_table3_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = res_0_V_write_assig_1_fu_2434_p1;

assign ap_return_1 = res_1_V_write_assig_1_fu_2446_p1;

assign ap_return_2 = res_2_V_write_assig_1_fu_2458_p1;

assign ap_return_3 = res_3_V_write_assig_1_fu_2470_p1;

assign exp_res_index_1_1_fu_2393_p3 = ((icmp13_reg_2733[0:0] === 1'b1) ? 10'd1023 : tmp_101_reg_2728);

assign exp_res_index_1_2_fu_2404_p3 = ((icmp14_reg_2743[0:0] === 1'b1) ? 10'd1023 : tmp_107_reg_2738);

assign exp_res_index_1_3_fu_2415_p3 = ((icmp15_reg_2753[0:0] === 1'b1) ? 10'd1023 : tmp_113_reg_2748);

assign exp_res_index_1_fu_2382_p3 = ((icmp12_reg_2723[0:0] === 1'b1) ? 10'd1023 : tmp_95_reg_2718);

assign exp_table2_address0 = tmp_25_0_1_fu_1718_p1;

assign exp_table2_address1 = tmp_25_0_2_fu_1735_p1;

assign exp_table2_address10 = tmp_25_3_1_fu_1888_p1;

assign exp_table2_address11 = tmp_25_3_2_fu_1905_p1;

assign exp_table2_address2 = tmp_25_0_3_fu_1752_p1;

assign exp_table2_address3 = tmp_25_1_fu_1769_p1;

assign exp_table2_address4 = tmp_25_1_2_fu_1786_p1;

assign exp_table2_address5 = tmp_25_1_3_fu_1803_p1;

assign exp_table2_address6 = tmp_25_2_fu_1820_p1;

assign exp_table2_address7 = tmp_25_2_1_fu_1837_p1;

assign exp_table2_address8 = tmp_25_2_3_fu_1854_p1;

assign exp_table2_address9 = tmp_25_3_fu_1871_p1;

assign icmp10_fu_1876_p2 = ((tmp_84_reg_2603 != 5'd0) ? 1'b1 : 1'b0);

assign icmp11_fu_1893_p2 = ((tmp_90_reg_2613 != 5'd0) ? 1'b1 : 1'b0);

assign icmp12_fu_2070_p2 = ((tmp_96_fu_2060_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp13_fu_2172_p2 = ((tmp_102_fu_2162_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp14_fu_2274_p2 = ((tmp_108_fu_2264_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp15_fu_2376_p2 = ((tmp_114_fu_2366_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp1_fu_1723_p2 = ((tmp_25_reg_2513 != 5'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_1740_p2 = ((tmp_36_reg_2523 != 5'd0) ? 1'b1 : 1'b0);

assign icmp3_fu_1757_p2 = ((tmp_42_reg_2533 != 5'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_1774_p2 = ((tmp_48_reg_2543 != 5'd0) ? 1'b1 : 1'b0);

assign icmp5_fu_1791_p2 = ((tmp_54_reg_2553 != 5'd0) ? 1'b1 : 1'b0);

assign icmp6_fu_1808_p2 = ((tmp_60_reg_2563 != 5'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_1825_p2 = ((tmp_66_reg_2573 != 5'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_1842_p2 = ((tmp_72_reg_2583 != 5'd0) ? 1'b1 : 1'b0);

assign icmp9_fu_1859_p2 = ((tmp_78_reg_2593 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_fu_1706_p2 = ((tmp_13_reg_2503 != 5'd0) ? 1'b1 : 1'b0);

assign index_0_1_cast_fu_408_p2 = (15'd512 + tmp_6_fu_398_p1);

assign index_0_1_fu_402_p2 = (16'd512 + p_5_0_1_fu_390_p3);

assign index_0_2_cast_fu_526_p2 = (15'd512 + tmp_19_fu_516_p1);

assign index_0_2_fu_520_p2 = (16'd512 + p_5_0_2_fu_508_p3);

assign index_0_3_cast_fu_644_p2 = (15'd512 + tmp_32_fu_634_p1);

assign index_0_3_fu_638_p2 = (16'd512 + p_5_0_3_fu_626_p3);

assign index_119_2_cast_fu_872_p2 = (15'd512 + tmp_45_fu_862_p1);

assign index_119_2_fu_866_p2 = (16'd512 + p_5_1_2_fu_854_p3);

assign index_119_3_cast_fu_986_p2 = (15'd512 + tmp_51_fu_976_p1);

assign index_119_3_fu_980_p2 = (16'd512 + p_5_1_3_fu_968_p3);

assign index_1_0_1_fu_1711_p3 = ((icmp_fu_1706_p2[0:0] === 1'b1) ? 10'd1023 : tmp_11_reg_2498);

assign index_1_0_2_fu_1728_p3 = ((icmp1_fu_1723_p2[0:0] === 1'b1) ? 10'd1023 : tmp_23_reg_2508);

assign index_1_0_3_fu_1745_p3 = ((icmp2_fu_1740_p2[0:0] === 1'b1) ? 10'd1023 : tmp_34_reg_2518);

assign index_1_1_2_fu_1779_p3 = ((icmp4_fu_1774_p2[0:0] === 1'b1) ? 10'd1023 : tmp_47_reg_2538);

assign index_1_1_3_fu_1796_p3 = ((icmp5_fu_1791_p2[0:0] === 1'b1) ? 10'd1023 : tmp_53_reg_2548);

assign index_1_1_fu_1762_p3 = ((icmp3_fu_1757_p2[0:0] === 1'b1) ? 10'd1023 : tmp_41_reg_2528);

assign index_1_2_1_fu_1830_p3 = ((icmp7_fu_1825_p2[0:0] === 1'b1) ? 10'd1023 : tmp_65_reg_2568);

assign index_1_2_3_fu_1847_p3 = ((icmp8_fu_1842_p2[0:0] === 1'b1) ? 10'd1023 : tmp_71_reg_2578);

assign index_1_2_fu_1813_p3 = ((icmp6_fu_1808_p2[0:0] === 1'b1) ? 10'd1023 : tmp_59_reg_2558);

assign index_1_3_1_fu_1881_p3 = ((icmp10_fu_1876_p2[0:0] === 1'b1) ? 10'd1023 : tmp_83_reg_2598);

assign index_1_3_2_fu_1898_p3 = ((icmp11_fu_1893_p2[0:0] === 1'b1) ? 10'd1023 : tmp_89_reg_2608);

assign index_1_3_fu_1864_p3 = ((icmp9_fu_1859_p2[0:0] === 1'b1) ? 10'd1023 : tmp_77_reg_2588);

assign index_2_1_cast_fu_1214_p2 = (15'd512 + tmp_63_fu_1204_p1);

assign index_2_1_fu_1208_p2 = (16'd512 + p_5_2_1_fu_1196_p3);

assign index_2_3_cast_fu_1328_p2 = (15'd512 + tmp_69_fu_1318_p1);

assign index_2_3_fu_1322_p2 = (16'd512 + p_5_2_3_fu_1310_p3);

assign index_2_cast_fu_1100_p2 = (15'd512 + tmp_57_fu_1090_p1);

assign index_2_fu_1094_p2 = (16'd512 + p_5_2_fu_1082_p3);

assign index_3_1_cast_fu_1556_p2 = (15'd512 + tmp_81_fu_1546_p1);

assign index_3_1_fu_1550_p2 = (16'd512 + p_5_3_1_fu_1538_p3);

assign index_3_2_cast_fu_1670_p2 = (15'd512 + tmp_87_fu_1660_p1);

assign index_3_2_fu_1664_p2 = (16'd512 + p_5_3_2_fu_1652_p3);

assign index_3_cast_fu_1442_p2 = (15'd512 + tmp_75_fu_1432_p1);

assign index_3_fu_1436_p2 = (16'd512 + p_5_3_fu_1424_p3);

assign index_cast_fu_758_p2 = (15'd512 + tmp_39_fu_748_p1);

assign index_s_fu_752_p2 = (16'd512 + p_5_1_fu_740_p3);

assign invert_table3_address0 = tmp_26_fu_2388_p1;

assign invert_table3_address1 = tmp_19_1_fu_2399_p1;

assign invert_table3_address2 = tmp_19_2_fu_2410_p1;

assign invert_table3_address3 = tmp_19_3_fu_2421_p1;

assign p_0_1_fu_382_p3 = ((tmp_22_0_1_fu_370_p2[0:0] === 1'b1) ? p_Result_3_0_1_cas_fu_346_p1 : ret_V_3_0_1_fu_376_p2);

assign p_0_2_fu_500_p3 = ((tmp_22_0_2_fu_488_p2[0:0] === 1'b1) ? p_Result_3_0_2_cas_fu_464_p1 : ret_V_3_0_2_fu_494_p2);

assign p_0_3_fu_618_p3 = ((tmp_22_0_3_fu_606_p2[0:0] === 1'b1) ? p_Result_3_0_3_cas_fu_582_p1 : ret_V_3_0_3_fu_612_p2);

assign p_1_1_fu_2122_p3 = ((tmp_10_1_fu_2110_p2[0:0] === 1'b1) ? p_Result_cast_22_fu_2086_p1 : ret_V_1_1_fu_2116_p2);

assign p_1_20_fu_2020_p3 = ((tmp_24_fu_2008_p2[0:0] === 1'b1) ? p_Result_cast_fu_1984_p1 : ret_V_1_fu_2014_p2);

assign p_1_2_24_fu_2224_p3 = ((tmp_10_2_fu_2212_p2[0:0] === 1'b1) ? p_Result_4_cast_fu_2188_p1 : ret_V_1_2_fu_2218_p2);

assign p_1_2_fu_846_p3 = ((tmp_22_1_2_fu_834_p2[0:0] === 1'b1) ? p_Result_3_1_2_cas_fu_810_p1 : ret_V_3_1_2_fu_840_p2);

assign p_1_3_25_fu_2326_p3 = ((tmp_10_3_fu_2314_p2[0:0] === 1'b1) ? p_Result_3_cast_fu_2290_p1 : ret_V_1_3_fu_2320_p2);

assign p_1_3_fu_960_p3 = ((tmp_22_1_3_fu_948_p2[0:0] === 1'b1) ? p_Result_3_1_3_cas_fu_924_p1 : ret_V_3_1_3_fu_954_p2);

assign p_1_fu_732_p3 = ((tmp_22_1_fu_720_p2[0:0] === 1'b1) ? p_Result_3_1_cast_fu_696_p1 : ret_V_3_1_fu_726_p2);

assign p_2_1_23_fu_2150_p3 = ((tmp_100_fu_2142_p3[0:0] === 1'b1) ? 12'd0 : tmp_99_fu_2138_p1);

assign p_2_1_fu_1188_p3 = ((tmp_22_2_1_fu_1176_p2[0:0] === 1'b1) ? p_Result_3_2_1_cas_fu_1152_p1 : ret_V_3_2_1_fu_1182_p2);

assign p_2_21_fu_2048_p3 = ((tmp_94_fu_2040_p3[0:0] === 1'b1) ? 12'd0 : tmp_93_fu_2036_p1);

assign p_2_2_fu_2252_p3 = ((tmp_106_fu_2244_p3[0:0] === 1'b1) ? 12'd0 : tmp_105_fu_2240_p1);

assign p_2_3_26_fu_2354_p3 = ((tmp_112_fu_2346_p3[0:0] === 1'b1) ? 12'd0 : tmp_111_fu_2342_p1);

assign p_2_3_fu_1302_p3 = ((tmp_22_2_3_fu_1290_p2[0:0] === 1'b1) ? p_Result_3_2_3_cas_fu_1266_p1 : ret_V_3_2_3_fu_1296_p2);

assign p_2_fu_1074_p3 = ((tmp_22_2_fu_1062_p2[0:0] === 1'b1) ? p_Result_3_2_cast_fu_1038_p1 : ret_V_3_2_fu_1068_p2);

assign p_3_0_1_fu_422_p3 = ((tmp_8_fu_414_p3[0:0] === 1'b1) ? 15'd0 : index_0_1_cast_fu_408_p2);

assign p_3_0_2_fu_540_p3 = ((tmp_21_fu_532_p3[0:0] === 1'b1) ? 15'd0 : index_0_2_cast_fu_526_p2);

assign p_3_0_3_fu_658_p3 = ((tmp_33_fu_650_p3[0:0] === 1'b1) ? 15'd0 : index_0_3_cast_fu_644_p2);

assign p_3_1_18_fu_1530_p3 = ((tmp_22_3_1_fu_1518_p2[0:0] === 1'b1) ? p_Result_3_3_1_cas_fu_1494_p1 : ret_V_3_3_1_fu_1524_p2);

assign p_3_1_2_fu_886_p3 = ((tmp_46_fu_878_p3[0:0] === 1'b1) ? 15'd0 : index_119_2_cast_fu_872_p2);

assign p_3_1_3_fu_1000_p3 = ((tmp_52_fu_992_p3[0:0] === 1'b1) ? 15'd0 : index_119_3_cast_fu_986_p2);

assign p_3_1_fu_772_p3 = ((tmp_40_fu_764_p3[0:0] === 1'b1) ? 15'd0 : index_cast_fu_758_p2);

assign p_3_2_19_fu_1644_p3 = ((tmp_22_3_2_fu_1632_p2[0:0] === 1'b1) ? p_Result_3_3_2_cas_fu_1608_p1 : ret_V_3_3_2_fu_1638_p2);

assign p_3_2_1_fu_1228_p3 = ((tmp_64_fu_1220_p3[0:0] === 1'b1) ? 15'd0 : index_2_1_cast_fu_1214_p2);

assign p_3_2_3_fu_1342_p3 = ((tmp_70_fu_1334_p3[0:0] === 1'b1) ? 15'd0 : index_2_3_cast_fu_1328_p2);

assign p_3_2_fu_1114_p3 = ((tmp_58_fu_1106_p3[0:0] === 1'b1) ? 15'd0 : index_2_cast_fu_1100_p2);

assign p_3_3_1_fu_1570_p3 = ((tmp_82_fu_1562_p3[0:0] === 1'b1) ? 15'd0 : index_3_1_cast_fu_1556_p2);

assign p_3_3_2_fu_1684_p3 = ((tmp_88_fu_1676_p3[0:0] === 1'b1) ? 15'd0 : index_3_2_cast_fu_1670_p2);

assign p_3_3_fu_1456_p3 = ((tmp_76_fu_1448_p3[0:0] === 1'b1) ? 15'd0 : index_3_cast_fu_1442_p2);

assign p_3_fu_1416_p3 = ((tmp_22_3_fu_1404_p2[0:0] === 1'b1) ? p_Result_3_3_cast_fu_1380_p1 : ret_V_3_3_fu_1410_p2);

assign p_4_1_fu_2130_p3 = ((tmp_97_fu_2090_p3[0:0] === 1'b1) ? p_1_1_fu_2122_p3 : p_Result_cast_22_fu_2086_p1);

assign p_4_2_fu_2232_p3 = ((tmp_103_fu_2192_p3[0:0] === 1'b1) ? p_1_2_24_fu_2224_p3 : p_Result_4_cast_fu_2188_p1);

assign p_4_3_fu_2334_p3 = ((tmp_109_fu_2294_p3[0:0] === 1'b1) ? p_1_3_25_fu_2326_p3 : p_Result_3_cast_fu_2290_p1);

assign p_4_fu_2028_p3 = ((tmp_91_fu_1988_p3[0:0] === 1'b1) ? p_1_20_fu_2020_p3 : p_Result_cast_fu_1984_p1);

assign p_5_0_1_fu_390_p3 = ((tmp_2_fu_350_p3[0:0] === 1'b1) ? p_0_1_fu_382_p3 : p_Result_3_0_1_cas_fu_346_p1);

assign p_5_0_2_fu_508_p3 = ((tmp_15_fu_468_p3[0:0] === 1'b1) ? p_0_2_fu_500_p3 : p_Result_3_0_2_cas_fu_464_p1);

assign p_5_0_3_fu_626_p3 = ((tmp_28_fu_586_p3[0:0] === 1'b1) ? p_0_3_fu_618_p3 : p_Result_3_0_3_cas_fu_582_p1);

assign p_5_1_2_fu_854_p3 = ((tmp_43_fu_814_p3[0:0] === 1'b1) ? p_1_2_fu_846_p3 : p_Result_3_1_2_cas_fu_810_p1);

assign p_5_1_3_fu_968_p3 = ((tmp_49_fu_928_p3[0:0] === 1'b1) ? p_1_3_fu_960_p3 : p_Result_3_1_3_cas_fu_924_p1);

assign p_5_1_fu_740_p3 = ((tmp_37_fu_700_p3[0:0] === 1'b1) ? p_1_fu_732_p3 : p_Result_3_1_cast_fu_696_p1);

assign p_5_2_1_fu_1196_p3 = ((tmp_61_fu_1156_p3[0:0] === 1'b1) ? p_2_1_fu_1188_p3 : p_Result_3_2_1_cas_fu_1152_p1);

assign p_5_2_3_fu_1310_p3 = ((tmp_67_fu_1270_p3[0:0] === 1'b1) ? p_2_3_fu_1302_p3 : p_Result_3_2_3_cas_fu_1266_p1);

assign p_5_2_fu_1082_p3 = ((tmp_55_fu_1042_p3[0:0] === 1'b1) ? p_2_fu_1074_p3 : p_Result_3_2_cast_fu_1038_p1);

assign p_5_3_1_fu_1538_p3 = ((tmp_79_fu_1498_p3[0:0] === 1'b1) ? p_3_1_18_fu_1530_p3 : p_Result_3_3_1_cas_fu_1494_p1);

assign p_5_3_2_fu_1652_p3 = ((tmp_85_fu_1612_p3[0:0] === 1'b1) ? p_3_2_19_fu_1644_p3 : p_Result_3_3_2_cas_fu_1608_p1);

assign p_5_3_fu_1424_p3 = ((tmp_73_fu_1384_p3[0:0] === 1'b1) ? p_3_fu_1416_p3 : p_Result_3_3_cast_fu_1380_p1);

assign p_Result_2_1_fu_2102_p3 = {{tmp_98_fu_2098_p1}, {4'd0}};

assign p_Result_2_2_fu_2204_p3 = {{tmp_104_fu_2200_p1}, {4'd0}};

assign p_Result_2_3_fu_2306_p3 = {{tmp_110_fu_2302_p1}, {4'd0}};

assign p_Result_2_fu_2000_p3 = {{tmp_92_fu_1996_p1}, {4'd0}};

assign p_Result_3_0_1_cas_fu_346_p1 = $signed(tmp_1_fu_336_p4);

assign p_Result_3_0_2_cas_fu_464_p1 = $signed(tmp_3_fu_454_p4);

assign p_Result_3_0_3_cas_fu_582_p1 = $signed(tmp_5_fu_572_p4);

assign p_Result_3_1_2_cas_fu_810_p1 = $signed(tmp_9_fu_800_p4);

assign p_Result_3_1_3_cas_fu_924_p1 = $signed(tmp_s_fu_914_p4);

assign p_Result_3_1_cast_fu_696_p1 = $signed(tmp_7_fu_686_p4);

assign p_Result_3_2_1_cas_fu_1152_p1 = $signed(tmp_12_fu_1142_p4);

assign p_Result_3_2_3_cas_fu_1266_p1 = $signed(tmp_14_fu_1256_p4);

assign p_Result_3_2_cast_fu_1038_p1 = $signed(tmp_10_fu_1028_p4);

assign p_Result_3_3_1_cas_fu_1494_p1 = $signed(tmp_18_fu_1484_p4);

assign p_Result_3_3_2_cas_fu_1608_p1 = $signed(tmp_20_fu_1598_p4);

assign p_Result_3_3_cast_fu_1380_p1 = $signed(tmp_16_fu_1370_p4);

assign p_Result_3_cast_fu_2290_p1 = $signed(tmp_31_fu_2280_p4);

assign p_Result_4_cast_fu_2188_p1 = $signed(tmp_29_fu_2178_p4);

assign p_Result_5_0_1_fu_362_p3 = {{tmp_4_fu_358_p1}, {6'd0}};

assign p_Result_5_0_2_fu_480_p3 = {{tmp_17_fu_476_p1}, {6'd0}};

assign p_Result_5_0_3_fu_598_p3 = {{tmp_30_fu_594_p1}, {6'd0}};

assign p_Result_5_1_2_fu_826_p3 = {{tmp_44_fu_822_p1}, {6'd0}};

assign p_Result_5_1_3_fu_940_p3 = {{tmp_50_fu_936_p1}, {6'd0}};

assign p_Result_5_1_fu_712_p3 = {{tmp_38_fu_708_p1}, {6'd0}};

assign p_Result_5_2_1_fu_1168_p3 = {{tmp_62_fu_1164_p1}, {6'd0}};

assign p_Result_5_2_3_fu_1282_p3 = {{tmp_68_fu_1278_p1}, {6'd0}};

assign p_Result_5_2_fu_1054_p3 = {{tmp_56_fu_1050_p1}, {6'd0}};

assign p_Result_5_3_1_fu_1510_p3 = {{tmp_80_fu_1506_p1}, {6'd0}};

assign p_Result_5_3_2_fu_1624_p3 = {{tmp_86_fu_1620_p1}, {6'd0}};

assign p_Result_5_3_fu_1396_p3 = {{tmp_74_fu_1392_p1}, {6'd0}};

assign p_Result_cast_22_fu_2086_p1 = $signed(tmp_27_fu_2076_p4);

assign p_Result_cast_fu_1984_p1 = $signed(tmp_22_fu_1974_p4);

assign p_Val2_7_0_3_fu_1939_p2 = (tmp2_reg_2683 + tmp3_fu_1934_p2);

assign p_Val2_7_1_3_fu_1949_p2 = (tmp5_reg_2693 + tmp6_fu_1944_p2);

assign p_Val2_7_2_3_fu_1959_p2 = (tmp8_reg_2703 + tmp9_fu_1954_p2);

assign p_Val2_7_3_3_fu_1969_p2 = (tmp1_reg_2713 + tmp4_fu_1964_p2);

assign r_V_0_1_fu_330_p2 = ($signed(tmp_12_0_1_fu_322_p1) - $signed(tmp_13_0_1_fu_326_p1));

assign r_V_0_2_fu_448_p2 = ($signed(tmp_12_0_2_fu_444_p1) - $signed(tmp_13_0_1_fu_326_p1));

assign r_V_0_3_fu_566_p2 = ($signed(tmp_12_0_3_fu_562_p1) - $signed(tmp_13_0_1_fu_326_p1));

assign r_V_1_2_fu_794_p2 = ($signed(tmp_12_0_2_fu_444_p1) - $signed(tmp_12_0_1_fu_322_p1));

assign r_V_1_3_fu_908_p2 = ($signed(tmp_12_0_3_fu_562_p1) - $signed(tmp_12_0_1_fu_322_p1));

assign r_V_1_fu_680_p2 = ($signed(tmp_13_0_1_fu_326_p1) - $signed(tmp_12_0_1_fu_322_p1));

assign r_V_2_1_fu_1136_p2 = ($signed(tmp_12_0_1_fu_322_p1) - $signed(tmp_12_0_2_fu_444_p1));

assign r_V_2_3_fu_1250_p2 = ($signed(tmp_12_0_3_fu_562_p1) - $signed(tmp_12_0_2_fu_444_p1));

assign r_V_2_fu_1022_p2 = ($signed(tmp_13_0_1_fu_326_p1) - $signed(tmp_12_0_2_fu_444_p1));

assign r_V_3_1_fu_1478_p2 = ($signed(tmp_12_0_1_fu_322_p1) - $signed(tmp_12_0_3_fu_562_p1));

assign r_V_3_2_fu_1592_p2 = ($signed(tmp_12_0_2_fu_444_p1) - $signed(tmp_12_0_3_fu_562_p1));

assign r_V_3_fu_1364_p2 = ($signed(tmp_13_0_1_fu_326_p1) - $signed(tmp_12_0_3_fu_562_p1));

assign res_0_V_write_assig_1_fu_2434_p1 = res_0_V_write_assig_fu_2426_p3;

assign res_0_V_write_assig_fu_2426_p3 = {{invert_table3_q0}, {14'd0}};

assign res_1_V_write_assig_1_fu_2446_p1 = res_1_V_write_assig_fu_2438_p3;

assign res_1_V_write_assig_fu_2438_p3 = {{invert_table3_q1}, {14'd0}};

assign res_2_V_write_assig_1_fu_2458_p1 = res_2_V_write_assig_fu_2450_p3;

assign res_2_V_write_assig_fu_2450_p3 = {{invert_table3_q2}, {14'd0}};

assign res_3_V_write_assig_1_fu_2470_p1 = res_3_V_write_assig_fu_2462_p3;

assign res_3_V_write_assig_fu_2462_p3 = {{invert_table3_q3}, {14'd0}};

assign ret_V_1_1_fu_2116_p2 = ($signed(13'd1) + $signed(p_Result_cast_22_fu_2086_p1));

assign ret_V_1_2_fu_2218_p2 = ($signed(13'd1) + $signed(p_Result_4_cast_fu_2188_p1));

assign ret_V_1_3_fu_2320_p2 = ($signed(13'd1) + $signed(p_Result_3_cast_fu_2290_p1));

assign ret_V_1_fu_2014_p2 = ($signed(13'd1) + $signed(p_Result_cast_fu_1984_p1));

assign ret_V_3_0_1_fu_376_p2 = ($signed(16'd1) + $signed(p_Result_3_0_1_cas_fu_346_p1));

assign ret_V_3_0_2_fu_494_p2 = ($signed(16'd1) + $signed(p_Result_3_0_2_cas_fu_464_p1));

assign ret_V_3_0_3_fu_612_p2 = ($signed(16'd1) + $signed(p_Result_3_0_3_cas_fu_582_p1));

assign ret_V_3_1_2_fu_840_p2 = ($signed(16'd1) + $signed(p_Result_3_1_2_cas_fu_810_p1));

assign ret_V_3_1_3_fu_954_p2 = ($signed(16'd1) + $signed(p_Result_3_1_3_cas_fu_924_p1));

assign ret_V_3_1_fu_726_p2 = ($signed(16'd1) + $signed(p_Result_3_1_cast_fu_696_p1));

assign ret_V_3_2_1_fu_1182_p2 = ($signed(16'd1) + $signed(p_Result_3_2_1_cas_fu_1152_p1));

assign ret_V_3_2_3_fu_1296_p2 = ($signed(16'd1) + $signed(p_Result_3_2_3_cas_fu_1266_p1));

assign ret_V_3_2_fu_1068_p2 = ($signed(16'd1) + $signed(p_Result_3_2_cast_fu_1038_p1));

assign ret_V_3_3_1_fu_1524_p2 = ($signed(16'd1) + $signed(p_Result_3_3_1_cas_fu_1494_p1));

assign ret_V_3_3_2_fu_1638_p2 = ($signed(16'd1) + $signed(p_Result_3_3_2_cas_fu_1608_p1));

assign ret_V_3_3_fu_1410_p2 = ($signed(16'd1) + $signed(p_Result_3_3_cast_fu_1380_p1));

assign tmp1_fu_1928_p2 = (exp_table2_q11 + exp_table2_q10);

assign tmp2_fu_1910_p2 = (exp_table2_q0 + exp_table2_q1);

assign tmp3_fu_1934_p2 = (18'd1024 + exp_table2_load_2_reg_2678);

assign tmp4_fu_1964_p2 = (18'd1024 + exp_table2_load_9_reg_2708);

assign tmp5_fu_1916_p2 = (exp_table2_q3 + exp_table2_q4);

assign tmp6_fu_1944_p2 = (18'd1024 + exp_table2_load_5_reg_2688);

assign tmp8_fu_1922_p2 = (exp_table2_q6 + exp_table2_q7);

assign tmp9_fu_1954_p2 = (18'd1024 + exp_table2_load_8_reg_2698);

assign tmp_100_fu_2142_p3 = p_4_1_fu_2130_p3[32'd12];

assign tmp_101_fu_2158_p1 = p_2_1_23_fu_2150_p3[9:0];

assign tmp_102_fu_2162_p4 = {{p_2_1_23_fu_2150_p3[11:10]}};

assign tmp_103_fu_2192_p3 = p_Val2_7_2_3_fu_1959_p2[32'd17];

assign tmp_104_fu_2200_p1 = p_Val2_7_2_3_fu_1959_p2[5:0];

assign tmp_105_fu_2240_p1 = p_4_2_fu_2232_p3[11:0];

assign tmp_106_fu_2244_p3 = p_4_2_fu_2232_p3[32'd12];

assign tmp_107_fu_2260_p1 = p_2_2_fu_2252_p3[9:0];

assign tmp_108_fu_2264_p4 = {{p_2_2_fu_2252_p3[11:10]}};

assign tmp_109_fu_2294_p3 = p_Val2_7_3_3_fu_1969_p2[32'd17];

assign tmp_10_1_fu_2110_p2 = ((p_Result_2_1_fu_2102_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_10_2_fu_2212_p2 = ((p_Result_2_2_fu_2204_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_10_3_fu_2314_p2 = ((p_Result_2_3_fu_2306_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_10_fu_1028_p4 = {{r_V_2_fu_1022_p2[32:18]}};

assign tmp_110_fu_2302_p1 = p_Val2_7_3_3_fu_1969_p2[5:0];

assign tmp_111_fu_2342_p1 = p_4_3_fu_2334_p3[11:0];

assign tmp_112_fu_2346_p3 = p_4_3_fu_2334_p3[32'd12];

assign tmp_113_fu_2362_p1 = p_2_3_26_fu_2354_p3[9:0];

assign tmp_114_fu_2366_p4 = {{p_2_3_26_fu_2354_p3[11:10]}};

assign tmp_11_fu_430_p1 = p_3_0_1_fu_422_p3[9:0];

assign tmp_12_0_1_fu_322_p1 = $signed(data_1_V_read);

assign tmp_12_0_2_fu_444_p1 = $signed(data_2_V_read);

assign tmp_12_0_3_fu_562_p1 = $signed(data_3_V_read);

assign tmp_12_fu_1142_p4 = {{r_V_2_1_fu_1136_p2[32:18]}};

assign tmp_13_0_1_fu_326_p1 = $signed(data_0_V_read);

assign tmp_14_fu_1256_p4 = {{r_V_2_3_fu_1250_p2[32:18]}};

assign tmp_15_fu_468_p3 = r_V_0_2_fu_448_p2[32'd32];

assign tmp_16_fu_1370_p4 = {{r_V_3_fu_1364_p2[32:18]}};

assign tmp_17_fu_476_p1 = r_V_0_2_fu_448_p2[17:0];

assign tmp_18_fu_1484_p4 = {{r_V_3_1_fu_1478_p2[32:18]}};

assign tmp_19_1_fu_2399_p1 = exp_res_index_1_1_fu_2393_p3;

assign tmp_19_2_fu_2410_p1 = exp_res_index_1_2_fu_2404_p3;

assign tmp_19_3_fu_2421_p1 = exp_res_index_1_3_fu_2415_p3;

assign tmp_19_fu_516_p1 = p_5_0_2_fu_508_p3[14:0];

assign tmp_1_fu_336_p4 = {{r_V_0_1_fu_330_p2[32:18]}};

assign tmp_20_fu_1598_p4 = {{r_V_3_2_fu_1592_p2[32:18]}};

assign tmp_21_fu_532_p3 = index_0_2_fu_520_p2[32'd15];

assign tmp_22_0_1_fu_370_p2 = ((p_Result_5_0_1_fu_362_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_0_2_fu_488_p2 = ((p_Result_5_0_2_fu_480_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_0_3_fu_606_p2 = ((p_Result_5_0_3_fu_598_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_1_2_fu_834_p2 = ((p_Result_5_1_2_fu_826_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_1_3_fu_948_p2 = ((p_Result_5_1_3_fu_940_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_1_fu_720_p2 = ((p_Result_5_1_fu_712_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_2_1_fu_1176_p2 = ((p_Result_5_2_1_fu_1168_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_2_3_fu_1290_p2 = ((p_Result_5_2_3_fu_1282_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_2_fu_1062_p2 = ((p_Result_5_2_fu_1054_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_3_1_fu_1518_p2 = ((p_Result_5_3_1_fu_1510_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_3_2_fu_1632_p2 = ((p_Result_5_3_2_fu_1624_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_3_fu_1404_p2 = ((p_Result_5_3_fu_1396_p3 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_22_fu_1974_p4 = {{p_Val2_7_0_3_fu_1939_p2[17:6]}};

assign tmp_23_fu_548_p1 = p_3_0_2_fu_540_p3[9:0];

assign tmp_24_fu_2008_p2 = ((p_Result_2_fu_2000_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_25_0_1_fu_1718_p1 = index_1_0_1_fu_1711_p3;

assign tmp_25_0_2_fu_1735_p1 = index_1_0_2_fu_1728_p3;

assign tmp_25_0_3_fu_1752_p1 = index_1_0_3_fu_1745_p3;

assign tmp_25_1_2_fu_1786_p1 = index_1_1_2_fu_1779_p3;

assign tmp_25_1_3_fu_1803_p1 = index_1_1_3_fu_1796_p3;

assign tmp_25_1_fu_1769_p1 = index_1_1_fu_1762_p3;

assign tmp_25_2_1_fu_1837_p1 = index_1_2_1_fu_1830_p3;

assign tmp_25_2_3_fu_1854_p1 = index_1_2_3_fu_1847_p3;

assign tmp_25_2_fu_1820_p1 = index_1_2_fu_1813_p3;

assign tmp_25_3_1_fu_1888_p1 = index_1_3_1_fu_1881_p3;

assign tmp_25_3_2_fu_1905_p1 = index_1_3_2_fu_1898_p3;

assign tmp_25_3_fu_1871_p1 = index_1_3_fu_1864_p3;

assign tmp_26_fu_2388_p1 = exp_res_index_1_fu_2382_p3;

assign tmp_27_fu_2076_p4 = {{p_Val2_7_1_3_fu_1949_p2[17:6]}};

assign tmp_28_fu_586_p3 = r_V_0_3_fu_566_p2[32'd32];

assign tmp_29_fu_2178_p4 = {{p_Val2_7_2_3_fu_1959_p2[17:6]}};

assign tmp_2_fu_350_p3 = r_V_0_1_fu_330_p2[32'd32];

assign tmp_30_fu_594_p1 = r_V_0_3_fu_566_p2[17:0];

assign tmp_31_fu_2280_p4 = {{p_Val2_7_3_3_fu_1969_p2[17:6]}};

assign tmp_32_fu_634_p1 = p_5_0_3_fu_626_p3[14:0];

assign tmp_33_fu_650_p3 = index_0_3_fu_638_p2[32'd15];

assign tmp_34_fu_666_p1 = p_3_0_3_fu_658_p3[9:0];

assign tmp_37_fu_700_p3 = r_V_1_fu_680_p2[32'd32];

assign tmp_38_fu_708_p1 = r_V_1_fu_680_p2[17:0];

assign tmp_39_fu_748_p1 = p_5_1_fu_740_p3[14:0];

assign tmp_3_fu_454_p4 = {{r_V_0_2_fu_448_p2[32:18]}};

assign tmp_40_fu_764_p3 = index_s_fu_752_p2[32'd15];

assign tmp_41_fu_780_p1 = p_3_1_fu_772_p3[9:0];

assign tmp_43_fu_814_p3 = r_V_1_2_fu_794_p2[32'd32];

assign tmp_44_fu_822_p1 = r_V_1_2_fu_794_p2[17:0];

assign tmp_45_fu_862_p1 = p_5_1_2_fu_854_p3[14:0];

assign tmp_46_fu_878_p3 = index_119_2_fu_866_p2[32'd15];

assign tmp_47_fu_894_p1 = p_3_1_2_fu_886_p3[9:0];

assign tmp_49_fu_928_p3 = r_V_1_3_fu_908_p2[32'd32];

assign tmp_4_fu_358_p1 = r_V_0_1_fu_330_p2[17:0];

assign tmp_50_fu_936_p1 = r_V_1_3_fu_908_p2[17:0];

assign tmp_51_fu_976_p1 = p_5_1_3_fu_968_p3[14:0];

assign tmp_52_fu_992_p3 = index_119_3_fu_980_p2[32'd15];

assign tmp_53_fu_1008_p1 = p_3_1_3_fu_1000_p3[9:0];

assign tmp_55_fu_1042_p3 = r_V_2_fu_1022_p2[32'd32];

assign tmp_56_fu_1050_p1 = r_V_2_fu_1022_p2[17:0];

assign tmp_57_fu_1090_p1 = p_5_2_fu_1082_p3[14:0];

assign tmp_58_fu_1106_p3 = index_2_fu_1094_p2[32'd15];

assign tmp_59_fu_1122_p1 = p_3_2_fu_1114_p3[9:0];

assign tmp_5_fu_572_p4 = {{r_V_0_3_fu_566_p2[32:18]}};

assign tmp_61_fu_1156_p3 = r_V_2_1_fu_1136_p2[32'd32];

assign tmp_62_fu_1164_p1 = r_V_2_1_fu_1136_p2[17:0];

assign tmp_63_fu_1204_p1 = p_5_2_1_fu_1196_p3[14:0];

assign tmp_64_fu_1220_p3 = index_2_1_fu_1208_p2[32'd15];

assign tmp_65_fu_1236_p1 = p_3_2_1_fu_1228_p3[9:0];

assign tmp_67_fu_1270_p3 = r_V_2_3_fu_1250_p2[32'd32];

assign tmp_68_fu_1278_p1 = r_V_2_3_fu_1250_p2[17:0];

assign tmp_69_fu_1318_p1 = p_5_2_3_fu_1310_p3[14:0];

assign tmp_6_fu_398_p1 = p_5_0_1_fu_390_p3[14:0];

assign tmp_70_fu_1334_p3 = index_2_3_fu_1322_p2[32'd15];

assign tmp_71_fu_1350_p1 = p_3_2_3_fu_1342_p3[9:0];

assign tmp_73_fu_1384_p3 = r_V_3_fu_1364_p2[32'd32];

assign tmp_74_fu_1392_p1 = r_V_3_fu_1364_p2[17:0];

assign tmp_75_fu_1432_p1 = p_5_3_fu_1424_p3[14:0];

assign tmp_76_fu_1448_p3 = index_3_fu_1436_p2[32'd15];

assign tmp_77_fu_1464_p1 = p_3_3_fu_1456_p3[9:0];

assign tmp_79_fu_1498_p3 = r_V_3_1_fu_1478_p2[32'd32];

assign tmp_7_fu_686_p4 = {{r_V_1_fu_680_p2[32:18]}};

assign tmp_80_fu_1506_p1 = r_V_3_1_fu_1478_p2[17:0];

assign tmp_81_fu_1546_p1 = p_5_3_1_fu_1538_p3[14:0];

assign tmp_82_fu_1562_p3 = index_3_1_fu_1550_p2[32'd15];

assign tmp_83_fu_1578_p1 = p_3_3_1_fu_1570_p3[9:0];

assign tmp_85_fu_1612_p3 = r_V_3_2_fu_1592_p2[32'd32];

assign tmp_86_fu_1620_p1 = r_V_3_2_fu_1592_p2[17:0];

assign tmp_87_fu_1660_p1 = p_5_3_2_fu_1652_p3[14:0];

assign tmp_88_fu_1676_p3 = index_3_2_fu_1664_p2[32'd15];

assign tmp_89_fu_1692_p1 = p_3_3_2_fu_1684_p3[9:0];

assign tmp_8_fu_414_p3 = index_0_1_fu_402_p2[32'd15];

assign tmp_91_fu_1988_p3 = p_Val2_7_0_3_fu_1939_p2[32'd17];

assign tmp_92_fu_1996_p1 = p_Val2_7_0_3_fu_1939_p2[5:0];

assign tmp_93_fu_2036_p1 = p_4_fu_2028_p3[11:0];

assign tmp_94_fu_2040_p3 = p_4_fu_2028_p3[32'd12];

assign tmp_95_fu_2056_p1 = p_2_21_fu_2048_p3[9:0];

assign tmp_96_fu_2060_p4 = {{p_2_21_fu_2048_p3[11:10]}};

assign tmp_97_fu_2090_p3 = p_Val2_7_1_3_fu_1949_p2[32'd17];

assign tmp_98_fu_2098_p1 = p_Val2_7_1_3_fu_1949_p2[5:0];

assign tmp_99_fu_2138_p1 = p_4_1_fu_2130_p3[11:0];

assign tmp_9_fu_800_p4 = {{r_V_1_2_fu_794_p2[32:18]}};

assign tmp_s_fu_914_p4 = {{r_V_1_3_fu_908_p2[32:18]}};

endmodule //softmax
